### ISSUE TITLE
psr2 indenting right after single line comment

### ISSUE THREAD

**Issue by l0c0luke** [dericofilho/sublime-phpfmt#101]
the below code 

```
// set db config
echo "- Setting global config so you don't do this again...\n";
```

will auto indent itself to

```
    // set db config
echo "- Setting global config so you don't do this again...\n";
```

if i put a space between the comment and the line below, it will auto indent correctly

**Comment by dericofilho** [comment]
@l0c0luke I am sorry for this bug. I could not reproduce the bug. Could you provide more code with more context to reproduce this? Also, if possible provide me with the content of the configuration file.

**Comment by l0c0luke** [comment]
```
{
	"enable_auto_align": false,
	"format_on_save": true,
	"indent_with_space": true,
	"passes":
	[
		"AlignTypehint",
		"StripExtraCommaInArray",
		"ReindentObjOps"
	],
	"psr2": true,
	"version": 2
}
```

this was the whole function after the auto formatting was done...

```
$console
    ->register('cms:setup')
    ->setDescription("Sets up the CMS environment.")
    ->setCode(
        function (InputInterface $input, OutputInterface $output) use ($app) {
            $public = __DIR__.'/some/class/path';

            // symlink the bundle public folder
            echo "- Setting up bundle public symlinks...\n";
            $link = __DIR__.'/../web/bundles/cms';

            if (is_link($link)) {
                echo "-- Symlink to public bundle folder has already been created.\n";
            } else {
                @symlink($public, $link);
                echo "-- SUCCESS! Symlink to bundle public folder created.\n";
            }

            // install or update bower
        echo "- Setting up CMS Bower components...\n";
            chdir($public);
            passthru('bower install');
        }
    );
```

**Comment by dericofilho** [comment]
I don't see the particular snippet you first posted. Are you sure the behavior is the same in both cases? I will fix it ASAP.

**Comment by l0c0luke** [comment]
i would focus on the full example ... notice the two echos getting plopped one indent left

**Comment by dericofilho** [comment]
I think I managed to reproduce it. I am working on it.

**Comment by dericofilho** [comment]
@l0c0luke please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/8a56458d28b267e6a5b87ed1390664ead2c3252f and try again.

**Comment by dericofilho** [comment]
@l0c0luke Success?

**Comment by l0c0luke** [comment]
ya looks good, you can close. thanks!


On Thu, Mar 12, 2015 at 5:52 AM, C Cirello <notifications@github.com> wrote:

> @l0c0luke <https://github.com/l0c0luke> Success?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/101#issuecomment-78473653>
> .
>



-- 

Luke Ollett

+1(949) 371-5292
