### ISSUE TITLE
Format removes _ in class names

### ISSUE THREAD

**Issue by Mech7** [dericofilho/sublime-phpfmt#102]
If i have an older classname from pre 5.4 era Zend_Something the class is renamed to ZendSomething so the autoloader does not work anymore as _ are mapped to directories.

**Comment by dericofilho** [comment]
@Mech7 I am really sorry for this bug. Please provide me with your configuration file and a snippet of code so I fix it ASAP.

**Comment by dericofilho** [comment]
@Mech7 Hello! Could you provide me with your configuration file and a snippet of code so I fix it ASAP?

**Comment by dericofilho** [comment]
@Mech7 hi, if I don't hear from you till 16th March, I shall close this issue.

**Comment by Mech7** [comment]
@dericofilho I am sorry think it's something with another plugin that is causing this, i just tried it at home and there it works fine.

**Comment by dericofilho** [comment]
@Mech7 Thanks for the feedback and for using the plugin.

**Comment by Mech7** [comment]
Sorry but am at work now and here the issue does exists, on mac at home linux i didn't have the problem.
it could also be that at home i have an older version:

Example
```
<?php
class Test_Legacy {
}
```

Run format now and..

```
<?php
class TestLegacy
{

}
```
My settings are:

```
{
	"version": 1,
	// "psr1":false,
	// "psr2":false,
	// "php_bin":"/usr/local/bin/php",
	// "indent_with_space":false,
	"format_on_save":false,
	"disable_auto_align":true
}
```

**Comment by dericofilho** [comment]
@Mech7 confirm to me the installed version you are running. By your configuration file, it seems an old installation or wrong configuration file. 

The configuration file has been updated to version 2 since last major release

**Comment by Mech7** [comment]
@dericofilho  the installed version is v2.6.2

**Comment by dericofilho** [comment]
So this configuration file is wrong. And from my own tests I couldn't reproduce the error. Please, remove the user configuration file, and reinstall the plugin. 

Then test if the error happened again

**Comment by Mech7** [comment]
I removed the user settings and now it work's ok it looks like the old user settings where copied over when removing and installing it again.
