### ISSUE TITLE
Project specific settings

### ISSUE THREAD

**Issue by simnom** [dericofilho/sublime-phpfmt#103]
Should the plugin allow for project specific settings?  Trying this out with:

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "phpfmt": {
        "version": 2,
        "psr1":false,
        "psr2":false,
        "indent_with_space":false,
    }
}
```

But, even with restarting ST3, this seems to be ignored.

Thanks

**Comment by dericofilho** [comment]
@simnom I am sorry for this inconvenience. Currently, sublime-phpfmt does not support per-project configuration. I have plans to introduce this support in the near future.

**Comment by simnom** [comment]
No problem, thanks for the reply.

**Comment by dericofilho** [comment]
I shall add this feature in the major version 3.

**Comment by dericofilho** [comment]
@simnom I have added the support for automatic search of ".php.tools.ini" file. In practice, it works as per-project configuration.

Upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.11.0 and give it a try. 
Add a .php.tools.ini in the root of your project, and within the file the same parameters from command line call to fmt.phar. For instance:

```
psr2=1
passes=ReturnNull
```

**Comment by simnom** [comment]
Hey, thanks for this but I'm struggling to get this working.  As a default I have the following as my user settings for the plugin:

```
{
	"enable_auto_align": true,
	"format_on_save": true,
	"passes":
	[
	],
	"psr2": true,
	"readini": true,
	"version": 2
}
```

I then have a `.php.tools.ini` in the project root (same folder as my `.sublime-project` file with the following:

```
format_on_save=0
```

i.e, I just want to disable the formatting on save for this project.  However the formatting still seems to get run.  Not sure if there's any debug info from the console I can provide to assist further.

Thanks

**Comment by dericofilho** [comment]
@simnom hi, I will check this out. I will keep you posted.

**Comment by dericofilho** [comment]
@simnom Now I know what happened. `.php.tools.ini` configures only the fmt.phar - not the plugin behavior itself. `Format on save` is a plugin behavior, whereas `PSR2` is the formatter configuration.

I am reopening this issue to find a better way to address this problem.

**Comment by bertelli** [comment]
PHP Version 5.5.10


System	Darwin USNYBERTFRALX9 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
Build Date	Apr 10 2014 17:21:18
Configure Command	'./configure' '--with-mysql=/Applications/MAMP/Library' '--with-apxs2=/Applications/MAMP/Library/bin/apxs' '--with-gd' '--with-jpeg-dir=/Applications/MAMP/Library' '--with-png-dir=/Applications/MAMP/Library' '--with-zlib' '--with-zlib-dir=/Applications/MAMP/Library' '--with-freetype-dir=/Applications/MAMP/Library' '--prefix=/Applications/MAMP/bin/php/php5.5.10' '--exec-prefix=/Applications/MAMP/bin/php/php5.5.10' '--sysconfdir=/Applications/MAMP/bin/php/php5.5.10/conf' '--with-config-file-path=/Applications/MAMP/bin/php/php5.5.10/conf' '--enable-ftp' '--enable-gd-native-ttf' '--with-bz2=/usr' '--with-ldap' '--with-mysqli=/Applications/MAMP/Library/bin/mysql_config' '--with-t1lib=/Applications/MAMP/Library' '--enable-mbstring=all' '--with-curl=/Applications/MAMP/Library' '--enable-sockets' '--enable-bcmath' '--with-imap=shared,/Applications/MAMP/Library/lib/imap-2007f' '--enable-soap' '--with-kerberos' '--enable-calendar' '--with-pgsql=shared,/Applications/MAMP/Library/pg' '--enable-exif' '--with-libxml-dir=/Applications/MAMP/Library' '--with-gettext=shared,/Applications/MAMP/Library' '--with-xsl=/Applications/MAMP/Library' '--with-pdo-mysql=shared,/Applications/MAMP/Library' '--with-pdo-pgsql=shared,/Applications/MAMP/Library/pg' '--with-mcrypt=shared,/Applications/MAMP/Library' '--with-openssl' '--enable-zip' '--with-iconv=/Applications/MAMP/Library' '--enable-opcache' '--enable-intl' '--with-tidy=shared' '--with-icu-dir=/Applications/MAMP/Library'
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/Applications/MAMP/bin/php/php5.5.10/conf
Loaded Configuration File	/Applications/MAMP/bin/php/php5.5.10/conf/php.ini

**Comment by dericofilho** [comment]
@simnom Please, update to https://github.com/dericofilho/sublime-phpfmt/releases/tag/3.0.0 and use the options `phpfmt: look for .php.tools.ini` and `phpfmt: toggle skip execution when .php.tools.ini is missing`.
