### ISSUE TITLE
Ternary operator in multiple lines

### ISSUE THREAD

**Issue by VladaPetrovic** [dericofilho/sublime-phpfmt#104]
When splitting ternary operators in multiple lines this is what I get.
```php
<?php

$isXSet = isset($x)
? 'set'
: 'not set';
```

If there a way to get this

```php
<?php

$isXSet = isset($x)
    ? 'set'
    : 'not set';
```

I use default settings.

**Comment by dericofilho** [comment]
@VladaPetrovic please add `IndentTernaryConditions` to `pass` in the configuration file. It should do the trick for you.

**Comment by matt-in-a-hat** [comment]
When I use `IndentTernaryConditions` in passes, the indentation that it adds to the ternary is in tabs even though indentation with space is enabled.

**Comment by VladaPetrovic** [comment]
@dericofilho it works! But even if I have `indent_with_space` set to `true` it adds tabs instead of spaces.

**Comment by dericofilho** [comment]
I am really sorry for this bug, I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@VladaPetrovic @matt-in-a-hat please update to https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.8.0

**Comment by VladaPetrovic** [comment]
It works! Thank you @dericofilho
