### ISSUE TITLE
abstract functions and psr-2 on following function

### ISSUE THREAD

**Issue by Helfull** [dericofilho/sublime-phpfmt#105]
Hey, just found out, if i have a abstract function followed by a normal function the psr-2 method doesnt get propper formatted

![Bad format](http://i.imgur.com/eqLVDl2.png)

you see the opening bracket is at the wrong place

psr-2 4.3

**Comment by dericofilho** [comment]
@Helfull I am really sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@Helfull please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/6036a2026fbae362504e75c6873ada3c26e50b46

I shall wait for your feedback before closing this issue.

**Comment by Helfull** [comment]
@dericofilho thanks man, its working now how ti supposed to
