### ISSUE TITLE
Recent error in Sublime Text 3 build 3082

### ISSUE THREAD

**Issue by patrickmaciel** [dericofilho/sublime-phpfmt#106]
When I try format my php code, or with auto format enabled I  get this error:

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "C:\Users\patrick_campos\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 1181, in run
        src = dofmt(self, self.view, None, src)
      File "C:\Users\patrick_campos\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 307, in dofmt
        p.stdin.write(src.encode('utf-8'))
    BrokenPipeError: [Errno 32] Broken pipe

**Comment by dericofilho** [comment]
@patrickmaciel I am really sorry for this inconvenience. Unfortunately, I need more context in order to be able to help you. I need: installed PHP version, PHP binary complete path, the plugin configuration file and the installed version of the plugin. 

Also please, try uninstalling and installing the plugin again - being sure that the user configuration file has been removed after the uninstall.

**Comment by patrickmaciel** [comment]
**PHP file I'm trying to format:** https://gist.github.com/patrickmaciel/f22a6f08226298f59611

**PHP Version:** 5.6.2 (using EasyPHP on Windows 7 x64)

**PHP Path:** C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\php.exe

**Obs.:** yesterday this error not occurs. Today Sublime Text 3 was updated... maybe is that.. I don't know.

Sorry for my english.

And of course: you plugin is awesome.

**Comment by dericofilho** [comment]
@patrickmaciel Unfortunately I don't have a Windows machine right now. So I will need few days to debug this issue. Meanwhile, have you had success with the reinstallation of the plugin?

**Comment by patrickmaciel** [comment]
I'll try to do that right now.

Obs.: I'm using windows at work only... at home I use mac. Tonight I'll validate if the same issue occurs  on mac too.

**Comment by patrickmaciel** [comment]
I remove the package and reinstall: same error.

I'll test on mac in about 3 hours.

**Comment by dericofilho** [comment]
I just tested it on a Windows VM and it worked fine. I cannot reproduce this bug.

**Comment by Shaked** [comment]
Could it be something related to the Python version ? 






On Fri, Mar 27, 2015 at 3:27 PM -0700, "C Cirello" <notifications@github.com> wrote:












I just tested it on a Windows VM and it worked fine. I cannot reproduce this bug.

**Comment by dericofilho** [comment]
@Shaked I believe that it is something related to permission. I remember once I tried to open sublime text through subl instead of sublime text.exe and few plug-ins had problems. I wouldn't be surprised if that was the case.

**Comment by dericofilho** [comment]
@patrickmaciel Any luck with your mac? When you reinstalled the plugin on your Windows machine, have you also removed the user configuration file?

**Comment by patrickmaciel** [comment]
Sorry for delay.

I test on my mac (yosemite) now and it's ok.

I don't know whats happend on my windows at work.

Obs.: I did not uninstall any programs on friday... I just power on, start sublime normally in start menu and this happened.

But, ok... I will other things and then I open other issue ok? Thanks for your time and sorry for my english.

**Comment by patrickmaciel** [comment]
Just for you knowledge:

- After I remove the options 'laravel style and save before save' the extension back to work.

**Comment by dericofilho** [comment]
Save before format?

**Comment by dericofilho** [comment]
@patrickmaciel I have tried with laravel style and save before format both turned on and I could not reproduce the issue.

**Comment by patrickmaciel** [comment]
@dericofilho strange.

I try, try, and try... and the error persist.

Then, I go the phpfmt user settings:

    {
        "disable_auto_align": true,
        "format_on_save": true,
        "indent_with_space": true,
        "laravel_style": true,
        "passes":
        [
        ],
        "psr1": true,
        "psr2": true,
        "save_before_format_now": true,
        "version": 2
    }

And I remove the **save_before_format** and **laravel_style** and works.

**Comment by dericofilho** [comment]
@patrickmaciel please add `"debug":true` and paste here the full output of the plugin.

**Comment by patrickmaciel** [comment]
phpfmt (oracle file): not found
    phpfmt (php version) out:
     PHP 5.5.15 (cli) (built: Jul 23 2014 15:05:09) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

    phpfmt (php version) err:
     
    cmd_fmt:  ['php', 'C:\\Users\\patrick_campos\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\fmt.phar', '--config=C:\\Users\\patrick_campos\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\php.tools.ini', '--psr1', '--psr1-naming', '--psr2', '--indent_with_space', '--smart_linebreak_after_curly', '--laravel', '-v', '-o=-', '-']
    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "C:\Users\patrick_campos\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 1202, in run
        src = dofmt(self, self.view, None, src)
      File "C:\Users\patrick_campos\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 327, in dofmt
        p.stdin.write(src.encode('utf-8'))
    BrokenPipeError: [Errno 32] Broken pipe

**Comment by dericofilho** [comment]
@patrickmaciel I just replicated this environment of yours here in my Windows VM and works just fine. I really have no idea on what's happening on your case.

**Comment by patrickmaciel** [comment]
@dericofilho No problem my friend it's works now.

I just need to remove this 2 options.

Thanks for your time :+1:

**Comment by mr-coder** [comment]
I've the exact problem. I disabled those two options that @patrickmaciel said but with no success. Any help?

**Comment by dericofilho** [comment]
@mr-coder `save_before_format` is an option I am about to deprecated. When you turn it off, do you have any success?

**Comment by mr-coder** [comment]
Not actually. This is my config file:

	{
	    "disable_auto_align": true,
	    "format_on_save": false,
	    "indent_with_space": false,
	    "laravel_style": false,
	    "passes":
	    [
	    ],
	    "psr1": true,
	    "psr2": true,
	    //"save_before_format_now": false,
	    "version": 2,
	    "php_bin":"D:/xampp/php/php.exe",
	    "debug": true,
	}

and then when I do a <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> on while being on a PHP file and choose `phpfmt: format now` this the log console shows:

	phpfmt (php version) err:
	 
	cmd_fmt:  ['D:/xampp/php/php.exe', '-dshort_open_tag=On', 'C:\\Users\\admin\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\fmt.phar', '--config=C:\\Users\\admin\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\php.tools.ini', '--psr1', '--psr1-naming', '--smart_linebreak_after_curly', '-v', '-o=-', '-']
	Traceback (most recent call last):
	  File "D:\Sublime Text 3\sublime_plugin.py", line 556, in run_
	    return self.run(edit)
	  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 843, in run
	    src = dofmt(self, self.view, None, src, True)
	  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 345, in dofmt
	    p.stdin.write(src.encode('utf-8'))
	BrokenPipeError: [Errno 32] Broken pipe

**Comment by dericofilho** [comment]
Removing the quote marks and pasting the code into stdin, what do you get when you run this manually?
`'D:/xampp/php/php.exe', '-dshort_open_tag=On', 'C:\\Users\\admin\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\fmt.phar', '--config=C:\\Users\\admin\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\php.tools.ini', '--psr1', '--psr1-naming', '--smart_linebreak_after_curly', '-v', '-o=-', '-'`

**Comment by mr-coder** [comment]
Is this right?

	"D:/xampp/php/php.exe" -dshort_open_tag=On "C:\\Users\\admin\\App
	Data\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\fmt.phar" --config="C:\\Users\\
	admin\\AppData\\Roaming\\Sublime Text 3\\Packages\\phpfmt\\php.tools.ini" --psr1
	 --psr1-naming --smart_linebreak_after_curly -v -o=- -

	Fatal error: Can't use function return value in write context in phar://C:/Users
	/admin/AppData/Roaming/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php on l
	ine 7197

	Call Stack:
	    0.0033     188696   1. {main}() C:\Users\admin\AppData\Roaming\Sublime Text
	3\Packages\phpfmt\fmt.phar:0

**Comment by dericofilho** [comment]
Yes. I am going to investigate it. I need more information.

The PHP version (for `/xampp/php/php.exe`), the plugin version too.

**Comment by mr-coder** [comment]
Thanks

**PHP v**: `PHP 5.4.7 (cli) (built: Sep 12 2012 23:48:31)`

**phpfmt v**: `2.17.0`

**Comment by dericofilho** [comment]
I will update the README.md file, but the minimum recommended version for PHP is PHP 5.5. Older PHP versions may or may not work, and they are no longer supported. Please, use a newer PHP version for the plugin. Download a newer version from PHP.net, and install it separately from XAMP.

**Comment by mr-coder** [comment]
Thanks. That was the key to solution. Upgraded to PHP v5.5.9 and now it works!
