### ISSUE TITLE
Weird OBJOP104.16.0 appearing after format

### ISSUE THREAD

**Issue by mike-anthony** [dericofilho/sublime-phpfmt#107]
Formatted this code:

    ))->addClass('ui-priority-secondary');

into

    )) OBJOP104.16.0 ->addClass('ui-priority-secondary');

What on earth?

**Comment by dericofilho** [comment]
@mike-anthony I am really sorry for this bug. This is very serious. I am fixing now. Please provide me with a longer piece of code in which this bug is reproduceable. 

For now, try disabling auto align.

**Comment by dericofilho** [comment]
@mike-anthony I am trying to release the fix to this bug now, but it seems GH is still under attack. Please, stick with me. I shall release an emergency upgrade soon.

**Comment by dericofilho** [comment]
@mike-anthony please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/fe4bcffad9d81976932984a1a081d10f2ea9eddd

**Comment by mike-anthony** [comment]
@dericofilho - Thanks. Here's a larger block:


		$importContainer->value = $importFromCSVButton->render();

		if ($this->modules->isInstalled('ProcessRedirects')) {

			$importFromRedirectsButton = $this->populateInputField($this->modules->get('InputfieldButton'), array(
				'id' => 'importFromRedirects',
				'href' => "{$this->importPath}?type=redirects",
				'value' => $this->_('Import from Redirects Module') . (($this->redirectsImported) ? ' ' . $this->_("(you've already done this)") : ''),
			)) OBJOP104.16.0 ->addClass('ui-priority-secondary');

			$importContainer->value .= $importFromRedirectsButton->render();

		}

Will try the update shortly :-)

**Comment by mike-anthony** [comment]
Fixed, thank you!
