### ISSUE TITLE
space_around_exclamation_mark

### ISSUE THREAD

**Issue by garyblankenship** [dericofilho/sublime-phpfmt#108]
Just installed.  I can't get space_around_exclamation_mark setting to work.  `if (!$this)` is what it gives me rather than `if ( ! $this)`even after toggling enabled, and trying to set it true in the settings json.

**Comment by dericofilho** [comment]
@garyblankenship I am sorry for this inconvenience. Could you please share with me your configuration file?

**Comment by dericofilho** [comment]
@garyblankenship Please, consider adding `SpaceAroundExclamationMark` in `pass` within your configuration file.

```
"passes":
	[
		"SpaceAroundExclamationMark"
	],
```

**Comment by garyblankenship** [comment]
@dericofilho Thanks, is this what you need?
`
{
    "space_around_exclamation_mark": true,
    "passes":["SpaceAroundExclamationMark"]
}
`

Isn't working for me yet.

**Comment by dericofilho** [comment]
Set space_around_exclamation_mark to false.

**Comment by garyblankenship** [comment]
yes, that worked.  Thank you!

**Comment by dericofilho** [comment]
@garyblankenship I know the naming is confusing. I plan to address this in the v3.
