### ISSUE TITLE
not working on OSX 10.9.5 + MAMPw/ PHP 5.5.10

### ISSUE THREAD

**Issue by bertelli** [dericofilho/sublime-phpfmt#109]
I'm trying to use this plugin, and despite i followed the instruction it doesn't do anything.
it seems setup correctly because I get no errors, but simply doesn't format anything.
You need to elaborate better your troubleshooting section.

**Comment by dericofilho** [comment]
@bertelli please add `"debug":true `  in your configuration file. Provide me with your PHP full path, the result of the console and your configuration file. Also, ensure you're formatting a valid php file.

As soon as I fix your case, I will extend the troubleshooting part with your case.

**Comment by bertelli** [comment]
ok let me do it. brb

**Comment by bertelli** [comment]
What do you mean by "result on the console"?

my config file

{
"version": 1,
"debug":true,
 //"psr1":false,
 //"psr2":false,
 "php_bin":"/usr/bin/php",
// "indent_with_space":false,
"format_on_save":true,
"disable_auto_align":false
}

I added debug:true, btw I created a file test.php with the code

<?php
for($i = 0; $i < 10; $i++)
{
if($i%2==0)
echo "Flip ";
}


and if i do ctrl+b i get

Flip Flip Flip Flip Flip [Finished in 0.1s]

**Comment by bertelli** [comment]
oh, i got the console:

phpfmt (php version) err:
 
cmd_fmt:  ['/usr/bin/php', '/Users/francesco.bertelli/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/francesco.bertelli/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--smart_linebreak_after_curly', '-v', '-o=-', '-']

**Comment by bertelli** [comment]
and

phpfmt (oracle file): not found
phpfmt (php version) out:
 PHP 5.4.30 (cli) (built: Jul 29 2014 23:43:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by dericofilho** [comment]
Is there nothing else before or after this line?

OK. PHP 5.4 is not supported. Please, replace 
`"php_bin":"/usr/bin/php",`
with the full path of your PHP installation (the PHP 5.5 version you have installed on your computer).

Also, keep in mind that the plugin does not format on build - at least not officially. Try saving first (cmd+s) before buildings.

**Comment by bertelli** [comment]
from phpinfo();

PHP Version 5.5.10


System	Darwin USNYBERTFRALX9 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
Build Date	Apr 10 2014 17:21:18
Configure Command	'./configure' '--with-mysql=/Applications/MAMP/Library' '--with-apxs2=/Applications/MAMP/Library/bin/apxs' '--with-gd' '--with-jpeg-dir=/Applications/MAMP/Library' '--with-png-dir=/Applications/MAMP/Library' '--with-zlib' '--with-zlib-dir=/Applications/MAMP/Library' '--with-freetype-dir=/Applications/MAMP/Library' '--prefix=/Applications/MAMP/bin/php/php5.5.10' '--exec-prefix=/Applications/MAMP/bin/php/php5.5.10' '--sysconfdir=/Applications/MAMP/bin/php/php5.5.10/conf' '--with-config-file-path=/Applications/MAMP/bin/php/php5.5.10/conf' '--enable-ftp' '--enable-gd-native-ttf' '--with-bz2=/usr' '--with-ldap' '--with-mysqli=/Applications/MAMP/Library/bin/mysql_config' '--with-t1lib=/Applications/MAMP/Library' '--enable-mbstring=all' '--with-curl=/Applications/MAMP/Library' '--enable-sockets' '--enable-bcmath' '--with-imap=shared,/Applications/MAMP/Library/lib/imap-2007f' '--enable-soap' '--with-kerberos' '--enable-calendar' '--with-pgsql=shared,/Applications/MAMP/Library/pg' '--enable-exif' '--with-libxml-dir=/Applications/MAMP/Library' '--with-gettext=shared,/Applications/MAMP/Library' '--with-xsl=/Applications/MAMP/Library' '--with-pdo-mysql=shared,/Applications/MAMP/Library' '--with-pdo-pgsql=shared,/Applications/MAMP/Library/pg' '--with-mcrypt=shared,/Applications/MAMP/Library' '--with-openssl' '--enable-zip' '--with-iconv=/Applications/MAMP/Library' '--enable-opcache' '--enable-intl' '--with-tidy=shared' '--with-icu-dir=/Applications/MAMP/Library'
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/Applications/MAMP/bin/php/php5.5.10/conf
Loaded Configuration File	/Applications/MAMP/bin/php/php5.5.10/conf/php.ini

**Comment by dericofilho** [comment]
>PHP 5.4 is not supported. Please, replace 
"php_bin":"/usr/bin/php",
with the full path of your PHP installation (the PHP 5.5 version you have installed on your computer).

It should be in `/Applications/MAMP/bin/php/php5.5.10/` somewhere.

**Comment by bertelli** [comment]
If i do that i get
Can't find PHP binary file at /Applications/MAMP/bin/php/php5.5.10

**Comment by dericofilho** [comment]
> It should be in /Applications/MAMP/bin/php/php5.5.10/ somewhere.

It means somewhere inside this folder. I don't know MAMP to pinpoint for you.

**Comment by bertelli** [comment]
OK NOW IT WORKS

{
"version": 1,
"debug":true,
 //"psr1":false,
 //"psr2":false,
 "php_bin":"/Applications/MAMP/bin/php/php5.5.10/bin/php",
// "indent_with_space":false,
"format_on_save":true,
"disable_auto_align":false
}

**Comment by bertelli** [comment]
I hope this can help anybody with MAMP + OSX!

**Comment by dericofilho** [comment]
I am glad it worked. In v3 I shall extend the troubleshooting session.

**Comment by bertelli** [comment]
cool! awesome plugin!

**Comment by dericofilho** [comment]
@bertelli Thanks for using it - spread the word.
