### ISSUE TITLE
Is this actually going away, or was it a dumb April Fools joke?

### ISSUE THREAD

**Issue by plaidfluff** [dericofilho/sublime-phpfmt#110]
Somewhere in the world, 31 March,
      
        Thank you for upgrading.
      
        Phpfmt was a nice idea but after lengthy debate with the user base,
      I came to understand that this actually works as training wheels on a bike
      - developers should always be responsible and format their code manually.
      
        Therefore, sublime-phpfmt will phase out feature per feature until
      you all learn to format code by yourselves.
      
        The very first feature that I am removing now is "phpfmt: toggle format
      on save".
      
        I hope everyone learns from this amazing tool.

That just sounds like a bad attempt at an April Fools joke to me. But I see no other open issues regarding it.  Maybe because it didn't get pushed out in a timely manner?

**Comment by dericofilho** [comment]
This is totally a meta of a joke. The perfect failed joke. :)
