### ISSUE TITLE
Please add a ST_CURLY_OPEN&&ST_CURLY_CLOSE wrap option.I want this

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#114]
USE PSR2 
Only this need to change
BEFORE
if ('article' == $type) {
	$config['upload_path'] = './uploads/source_image/';
} elseif ('category' == $type) {
	$config['upload_path'] = './uploads/category/';
} else {
	$config['upload_path'] = './uploads/adverts/';
}
AFTER
if ('article' == $type) 
{
	$config['upload_path'] = './uploads/source_image/';
} 
elseif ('category' == $type) 
{
	$config['upload_path'] = './uploads/category/';
} 
else 
{
	$config['upload_path'] = './uploads/adverts/';
}
BEFORE
while ($A <= 10) {
    # code...
}
AFTER
while ($A <= 10) 
{
    # code...
}
AND switch foreach  and so on

**Comment by dericofilho** [comment]
@adrianceding Please, consider adding `"AllmanStyleBraces"` to `pass` in your configuration file.

**Comment by adrianceding** [comment]
it works..thks
