### ISSUE TITLE
Laravel mode conflicts with PSR1, PSR2 modes

### ISSUE THREAD

**Issue by aa21** [dericofilho/sublime-phpfmt#115]
When you enable PSR1 or 2, formatter stops working. These errors are shown in debug console:

PHP Warning:  file_get_contents(/Users/aa21/Library/Application Support/Sublime Text 3/Packages/phpfmt/--psr1): failed to open stream: No such file or directory in phar:///Users/aa21/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar/fmt.stub.php on line 9679

same for PSR2. 

I'm on OSX yosemite.

**Comment by adrianceding** [comment]
toggle larval

**Comment by aa21** [comment]
@adrianceding Yup, figured the same thing out. It's a bug though. Shouldn't be conflicting with each other.

**Comment by dericofilho** [comment]
@aa21 I am sorry for this inconvenience. Could you please share your configuration file? I should like to have it in order to understand this bug better.

**Comment by dericofilho** [comment]
@aa21 I just managed to reproduce the bug. Laravel support is still in experimental phase, it is not fully compatible with PSR1/2. I don't have a time frame to make them both compatible. However, the formatter shouldn't crash the way it is crashing now. I am releasing a fix for the crash.

**Comment by dericofilho** [comment]
@aa21 Please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/c3e007ffdfa15835f5098a26a1c01871d04e2d9e

Very often, developers want to combine one or two features of one standard with one or two features of another standard. Please, consider taking a look at https://github.com/dericofilho/php.tools and check its options. You can always manually call parts of both standards and combine them freely - once you know them, all you need to do is declare them at `pass` configuration option within the plugin.
