### ISSUE TITLE
[BUG]when passes added AllmanStyleBraces.if inside the switch Dislocation 

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#116]
![image](https://cloud.githubusercontent.com/assets/4156079/7153845/8724a134-e382-11e4-9cca-b88a3f4a574e.png)

In front of IF should be 8 spaces or 2 tabs, but turned into 1 tab or 4 spaces

**Comment by dericofilho** [comment]
@adrianceding I am sorry for this bug, I shall fix it ASAP.

**Comment by adrianceding** [comment]
this plug-in is really great

**Comment by dericofilho** [comment]
@adrianceding I cannot reproduce this bug. Could you please share your configuration?

**Comment by adrianceding** [comment]
{
	"autocomplete": true,
	"autoimport": true,
	"cakephp_style": false,
	"enable_auto_align": true,
	"excludes":
	[
		"DoubleToSingleQuote",
		"IndentTernaryConditions"
	],
	"format_on_save": false,
	"indent_with_space": true,
	"laravel_style": false,
	"passes":
	[
		"StripExtraCommaInArray",
		"AlignTypehint",
		"AlignDoubleSlashComments",
		"MergeElseIf"
		// "AllmanStyleBraces"
	],
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"readini": true,
	"skip_if_ini_missing": true,
	"smart_linebreak_after_curly": false,
	"space_around_exclamation_mark": true,
	"version": 3,
	"vet": true,
	"visibility_order": false,
	"yoda": true
}

**Comment by dericofilho** [comment]
@adrianceding Please, upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/c3e007ffdfa15835f5098a26a1c01871d04e2d9e and try again.

**Comment by adrianceding** [comment]
@desricofilho 

![image](https://cloud.githubusercontent.com/assets/4156079/7160455/b1f8b286-e3bb-11e4-8a9c-3730e5889e18.png)


IF is worked.but ELSEIF and ELSE and so on.......

**Comment by dericofilho** [comment]
@adrianceding I will work more on this. Unfortunately I believe it will take time until this is 100%.

**Comment by dericofilho** [comment]
@adrianceding please, upgrade manually to https://github.com/dericofilho/sublime-phpfmt/commit/dd7dde794f5fade2e052fad8b72feba453a3d849

**Comment by adrianceding** [comment]
it worked.Thank you very much
