### ISSUE TITLE
[BUG]when passes added AllmanStyleBraces

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#117]
function After more than a blank line
![image](https://cloud.githubusercontent.com/assets/4156079/7172333/858502d8-e418-11e4-944d-2db938f57085.png)

**Comment by dericofilho** [comment]
@adrianceding I am sorry for this bug. I am going to fix it ASAP. Could you please confirm the toggle you want to mean with "after more than a blankline"?

**Comment by adrianceding** [comment]
![image](https://cloud.githubusercontent.com/assets/4156079/7175977/a25e9016-e44c-11e4-8c50-e9cc2d7f9d71.png)

**Comment by dericofilho** [comment]
@adrianceding I am afraid you didn't understand me. Please provide me with a longer piece of text, and your updated configuration file so I can reproduce this bug locally.

**Comment by adrianceding** [comment]
{
	"autocomplete": true,
	"autoimport": true,
	"cakephp_style": false,
	"enable_auto_align": true,
	"excludes":
	[
		"DoubleToSingleQuote",
		"IndentTernaryConditions"
	],
	"format_on_save": false,
	"indent_with_space": true,
	"laravel_style": false,
	"passes":
	[
		"StripExtraCommaInArray",
		"AlignTypehint",
		"AlignDoubleSlashComments",
		"MergeElseIf",
		"AllmanStyleBraces"
	],
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"readini": true,
	"skip_if_ini_missing": true,
	"smart_linebreak_after_curly": false,
	"space_around_exclamation_mark": true,
	"version": 3,
	"vet": true,
	"visibility_order": false,
	"yoda": true
}

**Comment by dericofilho** [comment]
@adrianceding  Please, upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/854896fdb7655f6d4881ae9ec57e3e12503028ce

**Comment by adrianceding** [comment]
all right

**Comment by dericofilho** [comment]
Solved?

**Comment by adrianceding** [comment]
yes

**Comment by dericofilho** [comment]
@adrianceding thanks for using the plugin
