### ISSUE TITLE
Inconsistent use of spaces before comments

### ISSUE THREAD

**Issue by leonklingele** [dericofilho/sublime-phpfmt#118]
Let's look at this formatted code:

    new TwitterOAuth(// Test comment	<-- No space before //
    	'012', // Consumer key
    	'345', // Consumer secret
    	'678', // OAuth token
    	'901'// OAuth token secret		<-- No space before //
    ); // Test comment
    
    if (true) {// Test comment			<-- No space before //
    	echo 'hi'; // Test comment
    }// Test comment					<-- No space before //

Each line has a comment at the end.
Sometimes a space is inserted before `//`, sometimes not.
It looks like a space before `//` (respectively `/*` and `#`) is only inserted after `,` or `;`.

This is no big issue, but looks a bit odd.

**Comment by dericofilho** [comment]
@leonklingele thanks for the input. I need to understand better these cases. It seems a legit request, but I will run against the test suite to see whether this impacts other spacing policies. I shall fix it ASAP, or at least provide you a feedback on this.

**Comment by dericofilho** [comment]
@leonklingele Please consider upgrading to https://github.com/dericofilho/sublime-phpfmt/commit/2828342c160c8e37f37307016dca644a25480654

**Comment by leonklingele** [comment]
Awesome, that fixed it :+1:

**Comment by dericofilho** [comment]
@leonklingele thanks for using the plugin.
