### ISSUE TITLE
indent_with_space: false doesn't work if using psr2

### ISSUE THREAD

**Issue by crimsonvspurple** [dericofilho/sublime-phpfmt#119]
"psr2": true,
	"indent_with_space": false,

Indentation is still done using spaces instead of tabs. Setting psr2 to false makes this option work as intended; false = tab; true = space.

**Comment by dericofilho** [comment]
@crimsonvspurple the PSR2 standard stipulates that all indentation is done with 4 spaces. Please, see https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#1-overview

However, very often people want one or two features of one standard, plus one or two features of another standard. Therefore, set `psr2` to `false`, and consider adding: 

`"PSR2KeywordsLowerCase","PSR2LnAfterNamespace","PSR2CurlyOpenNextLine","PSR2ModifierVisibilityStaticOrder","PSR2SingleEmptyLineAndStripClosingTag"` to `passes` in your configuration file.

**Comment by crimsonvspurple** [comment]
Yes, I'm aware of that. I just hate space indenting and just want everything psr1/2 except tabs instead of spaces.

So by adding these, I get psr2 (except spaces)? Nice!

btw, any docs on all the options for passes?

**Comment by dericofilho** [comment]
> So by adding these, I get psr2 (except spaces)? Nice!
Yes.

> btw, any docs on all the options for passes?

Yes, please check dericofilho/php.tools which is the engine for this plugin. `fmt.phar --list-passes` should provide with an extensive list of options.

**Comment by crimsonvspurple** [comment]
There seems to be very small bug/issue.

"PSR2CurlyOpenNextLine" is still using spaces.

so this:
    public function __construct()
    {
        # code...
    }

turns in to:
	public function __construct()
    {
		# code...
	}

**Comment by dericofilho** [comment]
@crimsonvspurple I am sorry for this bug. I shall fix it ASAP.

**Comment by crimsonvspurple** [comment]
No need to be sorry. Really appreciate your project/work and quick responses!
I'm glad to be able to contribute even just a little by finding a bug :)

**Comment by dericofilho** [comment]
@crimsonvspurple please, upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/178569190ea115b2a73af69958e1f8bd2f6562d0

**Comment by crimsonvspurple** [comment]
Just confirming that the fix is working! Thanks a lot.

**Comment by dericofilho** [comment]
@crimsonvspurple Thanks for using the plugin.
