### ISSUE TITLE
when add AllmanStyleBraces

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#120]
![image](https://cloud.githubusercontent.com/assets/4156079/7227769/cdacedf8-e785-11e4-9380-62abb145c004.png)

**Comment by adrianceding** [comment]
{
	"autocomplete": true,
	"autoimport": true,
	"cakephp_style": false,
	"enable_auto_align": true,
	"excludes":
	[
		"DoubleToSingleQuote",
		"IndentTernaryConditions"
	],
	"format_on_save": false,
	"indent_with_space": true,
	"laravel_style": false,
	"passes":
	[
		"StripExtraCommaInArray",
		"AlignTypehint",
		"AlignDoubleSlashComments",
		"MergeElseIf",
		"AllmanStyleBraces"
	],
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"readini": true,
	"skip_if_ini_missing": true,
	"smart_linebreak_after_curly": true,
	"space_around_exclamation_mark": true,
	"version": 3,
	"vet": true,
	"visibility_order": false,
	"yoda": true
}

**Comment by dericofilho** [comment]
@adrianceding I am sorry for this bug, I shall fix it ASAP.

**Comment by dericofilho** [comment]
@adrianceding please, upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/a1165b909d53ed96eb23832e02791fd1a26dcfec
