### ISSUE TITLE
Indent with 2 spaces or 4.

### ISSUE THREAD

**Issue by joelpittet** [dericofilho/sublime-phpfmt#121]
Looking from Drupal coding standards was wondering if this is a possibility?
https://www.drupal.org/coding-standards

**Comment by dericofilho** [comment]
@joelpittet Yes. Please consider adding this to the configuration file:
```
{
...
"indent_with_space": 2,
...
}
```

**Comment by joelpittet** [comment]
Cool, wonder why I couldn't spot that while searching the code base.


On Thursday, April 23, 2015, C Cirello <notifications@github.com> wrote:

> @joelpittet <https://github.com/joelpittet> Yes. Please consider adding
> this to the configuration file:
>
> {
> ...
> "indent_with_space": 2,
> ...
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/121#issuecomment-95806408>
> .
>


-- 
---------------------------------------
Joel Pittet
Joel Pittet Code & Design
Email: joel@pittet.ca
Skype: joelpittet
Website: pittet.ca
Cell: 604-369-3963

**Comment by dericofilho** [comment]
I need to work more on the documentation as well.
