### ISSUE TITLE
About translate_tabs_to_spaces

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#122]
Can i disable this option.i dont want tab translate to spaces and i hope auto aling use tab.

**Comment by dericofilho** [comment]
@adrianceding Auto-align will always use spaces. Unfortunately, this is a restriction of the auto-align. 

In order to prevent the translation from tabs to space, consider adding to your configuration file:
```
{
...
"excludes": ["PSR2IndentWithSpace"],
...
}
```
