### ISSUE TITLE
bug when `IF`  in  `CASE`

### ISSUE THREAD

**Issue by New-Future** [dericofilho/sublime-phpfmt#124]
before
---------
```php
function A()
{
	switch ($K)
	{
		case 1:
			if ($con)
			{//when there is a '{',all format will be wrong 
				//do ...
			}
			break;
		default:
			//do
	}
}

function B()
{
	//do
}
```

after
---------
```php
function A()
{
	switch ($K)
	{
		case 1:
			if ($con)
			{
				//do ...
			}
			break;
		default:
			//do
	}
}

function B()
	{//like this
	//do
}
```

**Comment by dericofilho** [comment]
@New-Future I am really sorry for this bug. Please, paste here your configuration file so I can reproduce this bug.

**Comment by dericofilho** [comment]
@New-Future I am really sorry for this bug. Please, paste here your configuration file so I can reproduce this bug.

**Comment by New-Future** [comment]
```json
{
	"format_on_save": false,
	"laravel_style": true,
	"passes":
	[
		"SpaceBetweenMethods",
		"MergeElseIf",
		"DoubleToSingleQuote"
	],
	"php_bin": "E:\\wamp\\bin\\php\\php5.5.12\\php.exe",
	"space_around_exclamation_mark": true,
	"version": 3
}
```
thanks @dericofilho .
your replay is so fast :smile_cat:

**Comment by dericofilho** [comment]
@New-Future Thanks for the information. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@New-Future Please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/456b4de9ffbe447da7e99ff828bcfcf83634352f

I should like to have your feedback before closing this issue.

**Comment by New-Future** [comment]
Great! Bug is fixed!  
Thanks you @dericofilho  :+1:
