### ISSUE TITLE
Code gets deleted on save

### ISSUE THREAD

**Issue by mscarchilli** [dericofilho/sublime-phpfmt#125]
When saving a document, some of the php code is getting deleted. While it can be useful, it is also not always wanted, especially when working on shared code with other developers.

Would you also please put up an example of how to override individual features of the settings with the user settings, or please direct me to where you have an example as the main package setting file only has one example of how to turn on/off "format_on_save"? Some of the features are good, but others are not wanted. I had to dig around to even figure out why my code was getting deleted on save which was a bit of a time waster.

For one simple example, how do you turn off this deleting of the parentheses and whitespace?

This:
```php
<?php include( $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php'); ?>
```
Turning into this:
```php
<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/life/head.php';?>
```

Here is an example (Nette PHP Framework) of the code getting deleted when it should not.

Before:
```php
namespace App\Presenters;

use Nette,
	App\Model;

/**
 * Homepage presenter.
 */
class HomepagePresenter extends BasePresenter
{

	public function renderDefault()
	{
		$this->template->anyVariable = 'any value';
	}

```

After:
```php
namespace App\Presenters;

/**
 * Homepage presenter.
 */
class HomepagePresenter extends BasePresenter {

	public function renderDefault() {
		$this->template->anyVariable = 'any value';
	}

}
```

Also you are missing a comma  after the 2 in the default settings.
```javascript
{
"version": 2
// "php_bin":"/usr/local/bin/php",
// "format_on_save":true,
}
```

**Comment by dericofilho** [comment]
@mscarchilli I am sorry for all these inconveniences. 

First, regarding this:
> Also you are missing a comma after the 2 in the default settings.

If I add the extra comma, it fails on my ST. I believe, if you have had the second line uncommented, the comma would then be necessary. 


Regarding, the removal of the T_USE constructs. You can disable this option by adding in your configuration file:

```
{
//...
	"excludes":["OrderUseClauses"],
//...
```


Regarding the removal of parentheses in include, you can disable this option by adding in your configuration file:

```
{
//...
	"excludes":[
		//...
		"RemoveIncludeParentheses",
		//...
	],
//...
```

I suggest you take a look at the README.md to see the possible options (https://github.com/dericofilho/sublime-phpfmt/blob/master/README.md)

In the case of formatting on save, you may want to summon, through command palette, the option `phpfmt: toggle format on save`.

It will update the configuration file accordingly.

**Comment by mscarchilli** [comment]
Excellent. Thank you for the quick response! :)

**Comment by dericofilho** [comment]
@mscarchilli Thanks for using the plugin.

**Comment by nardev** [comment]
Although i disabled "format_on_save" again i get this issue:

From this:
<?php

namespace Foo\Http\Controllers;

use Illuminate\Http\Request;

use Foo\Http\Requests;
use Foo\Http\Controllers\Controller;

use Foo\Http\Requests\UserSettingsSetRequest;

use Auth;
use Carbon;
use Log;
use Image;
use Storage;


When i save the file i get this:


<?php

namespace Foo\Http\Controllers;

use Auth;
use Foo\Http\Controllers\Controller;
use Foo\Http\Requests\UserSettingsSetRequest;
use Illuminate\Http\Request;
use Image;
use Storage;

**Comment by ccirello** [comment]
@nardev open a new issue and provide more context. Include configuration files,  and troubleshooting information from phpfmt command palette.
