### ISSUE TITLE
indent problem after <?php

### ISSUE THREAD

**Issue by vilkh3m** [dericofilho/sublime-phpfmt#126]
Hi i got small problem. I mix html and php in code and i go problem with indent code after open <?php

example:
```
<div>
    <div>
        <?php
            echo "test";
        ?>
    </div>
</div>
```
but after i use phpfmt i got this:
```
<div>
    <div>
        <?php
echo "test";
?>
    </div>
</div>
```
how configure phpfmt to format code like in first example ?

**Comment by Heart1010** [comment]
+1

**Comment by dericofilho** [comment]
@vilkh3m I am really sorry for this inconvenience. Right now, there is no configuration which allows the pretty printer to read from non-PHP code and affect PHP accordingly. 

The reason is that we cannot affirm that anything outside of PHP tags are always HTML. It would mean that this support would have to be adapted for several possibilities - each one with different expectations. More over, what's the difference between your request and 

```
<div>
    <div>
<?php
        echo "test";
?>
    </div>
</div>
```
Or even:
```
<div>
    <div><?php
echo "test";
?></div>
</div>
```

Let's take a step further, let's suppose the presence of JSON instead of HTML. How do I discriminate this:

```
{
       "value":"
<div>
<?php 
echo 1;
?>
</div>" 
} 
```
Should it indent based on HTML or based on JSON? 

That's the reason right now the phpfmt is PHP only, and not an universal pretty printer. 

I do not discard though making support for this - but I still need to solve all these problems.

**Comment by vilkh3m** [comment]
@dericofilho ok thx for answer in fact this is more complex that i think.

**Comment by dericofilho** [comment]
@vilkh3m way more complex. I am sorry.

**Comment by dericofilho** [comment]
@vilkh3m @Heart1010 Please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/58ff0ab6629a613b68f2d984aa4a060f61a277e5

and add `AlignPHPCode` to `passes` within your configuration file. See if it is what you had in mind.

**Comment by vilkh3m** [comment]
well i test this on some of my mixed code and its works great but in one case i get strange behave

earlier format make my code looks like this:
```
<table width="100%" border="1" cellspacing="1" cellpadding="10">
	<thead>
		<tr>
			<td><?=Yii::t('app', 'Param1')?></td>
			<td><?=Yii::t('app', 'Param2')?></td>
			<td><?=Yii::t('app', 'Param3')?></td>
			<td><?=Yii::t('app', 'Param4')?></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $name?></td>
			<td><?php foreach ($param2_arr as $key) {
	echo $key . ' ';
}
?></td>
			<td><?php foreach ($param3_arr as $key) {
	echo $key . ' ';
}
?></td>
			<td><?php foreach ($param4_arr as $v) {
	echo CHtml::link($v['name'], array('file', 'id' => $v['id'], 'typ' => '1')) . '<br>';
}
?></td>
		</tr>
	</tbody>
</table>
```
and now after patch add some TD's to my code:
```
<table width="100%" border="1" cellspacing="1" cellpadding="10">
	<thead>
		<tr>
			<td><?=Yii::t('app', 'Param1')?></td>
			<td><?=Yii::t('app', 'Param2')?></td>
			<td><?=Yii::t('app', 'Param3')?></td>
			<td><?=Yii::t('app', 'Param4')?></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>			<td><?php echo $name?></td>
			<td>			<td><?php foreach ($param2_arr as $key) {
			<td>		echo $key . ' ';
			<td>}
			<td>?></td>
			<td>			<td><?php foreach ($param3_arr as $key) {
			<td>		echo $key . ' ';
			<td>}
			<td>?></td>
			<td>			<td><?php foreach ($param4_arr as $v) {
			<td>		echo CHtml::link($v['name'], array('file', 'id' => $v['id'], 'typ' => '1')) . '<br>';
			<td>}
			<td>?></td>
		</tr>
	</tbody>
</table>
```

**Comment by dericofilho** [comment]
Upgrade to 3.14.0 it should be solved.

**Comment by vilkh3m** [comment]
in 3.14.0 looks this way:
```
<table width="100%" border="1" cellspacing="1" cellpadding="10">
	<thead>
		<tr>
			<td><?=Yii::t('app', 'Param1')?></td>
			<td><?=Yii::t('app', 'Param2')?></td>
			<td><?=Yii::t('app', 'Param3')?></td>
			<td><?=Yii::t('app', 'Param4')?></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>			    <?php echo $name?></td>
			<td>			    <?php foreach ($param2_arr as $key) {
			    		echo $key . ' ';
			    }
			    ?></td>
			<td>			    <?php foreach ($param3_arr as $key) {
			    		echo $key . ' ';
			    }
			    ?></td>
			<td>			    <?php foreach ($param4_arr as $v) {
			    		echo CHtml::link($v['name'], array('file', 'id' => $v['id'], 'typ' => '1')) . '<br>';
			    }
			    ?></td>
		</tr>
	</tbody>
</table>
```
its not perfect but it looks better :) thx for your work !

**Comment by vilkh3m** [comment]
oh no there another problem each format add new tabs

after couple format code:
```
<table width="100%" border="1" cellspacing="1" cellpadding="10">
	<thead>
		<tr>
			<td><?=Yii::t('app', 'Param1')?></td>
			<td><?=Yii::t('app', 'Param2')?></td>
			<td><?=Yii::t('app', 'Param3')?></td>
			<td><?=Yii::t('app', 'Param4')?></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>			    			    			    			    			    			    <?php echo $name?></td>
			<td>			    			    			    			    			    			    <?php foreach ($param2_arr as $key) {
			    			    			    			    			    			    		echo $key . ' ';
			    			    			    			    			    			    }
			    			    			    			    			    			    ?></td>
			<td>			    			    			    			    			    			    <?php foreach ($param3_arr as $key) {
			    			    			    			    			    			    		echo $key . ' ';
			    			    			    			    			    			    }
			    			    			    			    			    			    ?></td>
			<td>			    			    			    			    			    			    <?php foreach ($param4_arr as $v) {
			    			    			    			    			    			    		echo CHtml::link($v['name'], array('file', 'id' => $v['id'], 'typ' => '1')) . '<br>';
			    			    			    			    			    			    }
			    			    			    			    			    			    ?></td>
		</tr>
	</tbody>
</table>
```

**Comment by dericofilho** [comment]
@vilkh3m ok! I will fix it ASAP. It will take a while to stabilize this feature

**Comment by dericofilho** [comment]
@vilkh3m please, upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/2c9bca64cc7a949a5833064c282af1271f198310 and try again.

**Comment by vilkh3m** [comment]
@dericofilho well i test this and in most case works great but i find example that again tabs is adding each time i format code i record screencast wit this to help you
http://monosnap.com/file/iZMuKtq3zjulxufGcDGMGf4KF4aSuD

**Comment by dericofilho** [comment]
@vilkh3m please, send me in a gist that specific piece of code. I believe it could be some misinteraction with strings.

**Comment by vilkh3m** [comment]
https://gist.github.com/vilkh3m/170bd6b8e6f00444edfa

**Comment by dericofilho** [comment]
@vilkh3m Thanks, I managed to reproduce the bug.

**Comment by dericofilho** [comment]
@vilkh3m please, upgrade to https://github.com/dericofilho/sublime-phpfmt/tree/3.17.0

**Comment by vilkh3m** [comment]
close ! but still part of code got auto tabs each format
http://monosnap.com/file/Lkh6ZOWLxFJgDyshruLFDgIZDqPiQC

**Comment by dericofilho** [comment]
@vilkh3m ok! I guess it is an issue with string interpolation. I will check it ASAP.

**Comment by dericofilho** [comment]
@vilkh3m please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/3.17.1 and try again.

**Comment by vilkh3m** [comment]
now look great i can't find any problems :) THX !

**Comment by dericofilho** [comment]
@vilkh3m Thanks for using the plugin.

**Comment by vilkh3m** [comment]
@dericofilho Thanks for writing this plugin ! :)

**Comment by Heart1010** [comment]
Looking good here also... one "false indentation" detected in a big php/html file
This
```html
<div class="alert alert-dismissable alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>

                                <?php
                                	echo '<p><code>Fehler beim Datei-Upload:</code> ' . $e->getMessage() . '</p>';
                    	            echo '<p><br>Handelt es sich bei der hochgeladenen Datei wirklich um eine korrekte <code>CSV</code> Datei?</p>';
                    	            // echo '<pre>'; var_dump($e); die;
                                ?>
                                <p>&nbsp;</p>
...
```
is going to be the following after I do "format now"
```html
<div class="alert alert-dismissable alert-danger">
                                <button type="button" class="close" data-dismiss="alert">×</button>

                                <?php
                                	echo '<p><code>Fehler beim Datei-Upload:</code> ' . $e->getMessage() . '</p>';
                                	            echo '<p><br>Handelt es sich bei der hochgeladenen Datei wirklich um eine korrekte <code>CSV</code> Datei?</p>';
                                	            // echo '<pre>'; var_dump($e); die;
                                            ?>
                                <p>&nbsp;</p>
...
```
(I'm using v3.21.0 with "passes": [ "AlignPHPCode" ] in config,hope this has above new additions already in!?)

**Comment by dericofilho** [comment]
@Heart1010 could you please open another issue so I take look at this case ASAP?

**Comment by Heart1010** [comment]
@dericofilho sure... see #131
