### ISSUE TITLE
Can't install/update in Package control ST3

### ISSUE THREAD

**Issue by vilkh3m** [dericofilho/sublime-phpfmt#129]
Hi
Sublime Text 3 Package control try update/instal version 3.20.0 but there is no 3.20.0 in repo only 3.19.0 and 3.21.0

**Comment by dericofilho** [comment]
@vilkh3m I am sorry for this problem. I am working on it.

**Comment by dericofilho** [comment]
@vilkh3m Please, try again.

**Comment by vilkh3m** [comment]
works fine now, thx
