### ISSUE TITLE
How can I keep the unused use clauses

### ISSUE THREAD

**Issue by gfd6th** [dericofilho/sublime-phpfmt#130]
Hi,
I have a trouble about this feature.
But if I just only wanna make a test and remove some class. When I save the test file, it will remove the corresponding use clause. eg:

Before:
use Foo;
new Foo();

Format:
use Foo;
// new Foo();

**Comment by dericofilho** [comment]
@gfd6th I am sorry for this inconvenience. Please, in your configuration file use:

```
{
...
    "excludes": ["OrderUseClauses"],
...
}
```

**Comment by gfd6th** [comment]
Thanks for your replay.

I have tried this code in my User/Preferences.sublime-settings, User/phpfmt.sublime-settings, and Default/phpfmt.sublime-settings files in ST3.

Unfortunately, I still couldn't get rid of it.

Any wrong?

**Comment by dericofilho** [comment]
@gfd6th Please, paste in a gist the user configuration file for the plugin.

**Comment by gfd6th** [comment]
This is my sublime settings gits
https://github.com/gfd6th/sublime-setting

Maybe my expression confused you, I mean I wanna 
```php 
use Foo\A;
use Foo\B;

new B();
```

But the after phpfmt formatting, it will be:
```php
use Foo\B

new B();
```
the `use Foo\B` clause is removed, but I wanna keep this one.

**Comment by dericofilho** [comment]
@gfd6th I cannot reproduce this bug. I will need more context. Please, provide me a gist of the source code which it fails. It is designed to keep all use clauses which are referenced in the body.

**Comment by gfd6th** [comment]
This is my failed file gist.
https://github.com/gfd6th/phpfmt-testing-file
Thanks for your reply.

**Comment by dericofilho** [comment]
So you want to keep an unused "use". The solution I gave you ought to work. I will however double check locally.

**Comment by gfd6th** [comment]
Yeah,

So what I to do right now is comment this unused 'used' clause.
and after testing, I uncomment this use clause.

Any better solution for testing. I don't want to always press 'ctrl+z' to undo.

**Comment by dericofilho** [comment]
I managed to reproduce the bug. I am fixing it ASAP.

**Comment by dericofilho** [comment]
@gfd6th Please, update your configuration file to:

{
...
    "excludes": ["OrderUseClauses", "SortUseNameSpace"],
...
}

**Comment by gfd6th** [comment]
It seems to remove the unused "use" all before.

**Comment by dericofilho** [comment]
@gfd6th What do you mean?

**Comment by gfd6th** [comment]
It will still remove `use Illuminate\Http\Requestaaa;` when I save this file
https://github.com/gfd6th/phpfmt-testing-file/blob/master/Bar.php

**Comment by dericofilho** [comment]
@gfd6th I see. Are you sure you have updated your configuration file as I said last? With both options? I managed to keep `use Illuminate\Http\Requestaaa;` untouched with the configuration I gave you.

**Comment by gfd6th** [comment]
Sorry, I just updated the User/Preferences.sublime-settings.
It works when I update User/phpfmt.sublime-settings or Default/phpfmt.sublime-settings.
Thanks for your sincere help!! :-)

**Comment by a-moses** [comment]
Thank you ! 

 Please consider add it to readme file
