### ISSUE TITLE
Why phpfmt change class name

### ISSUE THREAD

**Issue by minhluan259** [dericofilho/sublime-phpfmt#132]
ex: 
class CategorySearch_Block_Form
to 
class CategorySearchBlockForm

I need phpfmt don't change class name.

**Comment by dericofilho** [comment]
@minhluan259 I am sorry for this inconvenience. Please, paste here your configuration file. Also, please try disabling `phpfmt: toggle PSR1 - Class and Methods names`.

**Comment by dericofilho** [comment]
@minhluan259 If I don't hear back until 5th June, I shall close this issue.
