### ISSUE TITLE
Document main settings

### ISSUE THREAD

**Issue by axelson** [dericofilho/sublime-phpfmt#133]
Settings such as indent_size and indent_with_space are not documented in `README.md`, it would be nice if they were. Ideally with information about how to edit the Sublime configuration file.

My particular issue is that I'm trying to change the indentation to use spaces instead of tabs, from #96 it looks like `indent_with_space` is the setting to change. Additionally I'm looking for a way to only format a block and not the whole file (although that might be best raised as a separate issue).

**Comment by dericofilho** [comment]
@axelson thanks for the suggestions. 

Regarding the documentation, I will work to improve it ASAP. As a matter of fact, I have plans to have it automatically generated by this project's cousin (php.tools). 

Regarding the option "format selection", it is something that this formatter had before, and it shall be introduced back in the next major release.

`indent_with_space` is the option you are looking for. Set it with the number of spaces you feel best.

**Comment by axelson** [comment]
Glad to hear it! Thanks for your help!
