### ISSUE TITLE
It can't work in window 7

### ISSUE THREAD

**Issue by winsonet** [dericofilho/sublime-phpfmt#134]
When I try to format my PHP code, I got the below errors:

~~~
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "C:\Users\winson\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 873, in run
    src = dofmt(self, self.view, None, src, True)
  File "C:\Users\winson\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 221, in dofmt
    p = subprocess.Popen(cmd_ver, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False, startupinfo=startupinfo)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] System can not find the file specified.
~~~

I am using PHP5.6, and also tried the PHP5.3 but still failed, any ideas?

Thanks!

**Comment by dericofilho** [comment]
@winsonet I am sorry for this inconvenience. Is this PHP installed on the same machine running ST? Have you updated the configuration file's `php_bin` with the full path of your local PHP installation?

**Comment by winsonet** [comment]
Yes, I have updated the settings and below is my settings:

~~~
{
"version": 2
"php_bin":"C:/Program Files (x86)/PHP/v5.6/php.exe",
// "format_on_save":true,
}
~~~

Did I miss anything?

Thanks!

**Comment by dericofilho** [comment]
@winsonet it should work with this. Please add `"debug":true` in the configuration file and paste console output here.

**Comment by winsonet** [comment]
I have update the config as below:
~~~
{
"version": 2
"php_bin":"C:/Program Files (x86)/PHP/v5.6/php.exe",
"debug":true,
// "format_on_save":true,
}
~~~

 but I just got the same error as above :(

**Comment by dericofilho** [comment]
@winsonet please paste here the console log output

**Comment by dericofilho** [comment]
@winsonet be sure to paste here the console output with the whole content, and not just the error message.

**Comment by winsonet** [comment]
Oh, I am so sorry, I found the issue, this is my mistake, I missed a comma in the config , after 
~~~
"version": 2
~~~
when I restart the ST, and just popup the error, so I can found it!

Thanks for your help, and your plugin is perfect :)

**Comment by dericofilho** [comment]
Thanks for using the plugin.
