### ISSUE TITLE
What if I want to add a Drupal Standard ?

### ISSUE THREAD

**Issue by killua99** [dericofilho/sublime-phpfmt#135]
There is a Drupal Standard and they don't use tabs for spaces. We use spaces for tabs, and 2 spaces (one tab) So there's a way to setup use space instead of tabs and how many we want?

**Comment by dericofilho** [comment]
@killua99 Yes. Have you considered using the command `phpfmt: indentation with spaces`? 
Have you considered adding this to your configuration file?
```
{
...
"indent_with_space": 2, // replace 2 with the number of spaces you want.
...
}
```

**Comment by dericofilho** [comment]
If I don't hear back until June 12th, I shall close this issue.

**Comment by killua99** [comment]
Yes, with that setting work, now they're spaces. Now I've some issue.

We work with this kind of code.

/*
function hundra_wattaren_preprocess_block(&$vars, $hook) {
  //  kpr($vars['content']);

  //lets look for unique block in a region $region-$blockcreator-$delta
   $block =
   $vars['elements']['#block']->region .'-'.
   $vars['elements']['#block']->module .'-'.
   $vars['elements']['#block']->delta;

  // print $block .' ';
   switch ($block) {
     case 'header-menu_block-2':
       $vars['classes_array'][] = '';
       break;
     case 'sidebar-system-navigation':
       $vars['classes_array'][] = '';
       break;
    default:

    break;

   }


  switch ($vars['elements']['#block']->region) {
    case 'header':
      $vars['classes_array'][] = '';
      break;
    case 'sidebar':
      $vars['classes_array'][] = '';
      $vars['classes_array'][] = '';
      break;
    default:

      break;
  }

}
*/

When I save them it format it to none space at all. It need a rule for big comments blocks to leave it as it

**Comment by dericofilho** [comment]
@killua99, Please consider adding this to plugin's configuration file:

```
"passes": ["RestoreComments"],
```

**Comment by dericofilho** [comment]
@killua99 also, keep in mind that commented code gets formatted once they are uncommented.

**Comment by dericofilho** [comment]
@killua99 if I don't hear back until June 13th, I shall close this issue.

**Comment by Saneesh** [comment]
@ccirello if you don't open this issue I shall close GitHub! :-P
