### ISSUE TITLE
ignore_list config setting causing plugin to not execute

### ISSUE THREAD

**Issue by rufhausen** [dericofilho/sublime-phpfmt#137]
The ignore_list entry in the config (you had suggested this in response to my comment in issue #131) is causing the plugin to fail. Formatting a file returns the following in the console:
Traceback (most recent call last):
File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
return self.run(edit)
File "/Users/gtaylor/Library/Application Support/Sublime Text 3/Packages/phpfmt/phpfmt.py", line 1350, in run
src = dofmt(self, self.view, None, src)
File "/Users/gtaylor/Library/Application Support/Sublime Text 3/Packages/phpfmt/phpfmt.py", line 162, in dofmt
ignore_list = ignore_list.split(" ")
AttributeError: 'list' object has no attribute 'split'

Full config:
{
	"autocomplete": false,
	"autoimport": false,
	"enable_auto_align": true,
	"excludes":
	[
		"WordWrap",
		"LeftWordWrap"
	],
	"format_on_save": true,
	"ignore_list":
	[
		".blade.php"
	],
	"indent_with_space": 4,
	"laravel_style": false,
	"passes":
	[
		"MergeNamespaceWithOpenTag",
		"RemoveUseLeadingSlash",
		"SpaceBetweenMethods",
		"PrettyPrintDocBlocks",
		"GeneratePHPDoc",
		"AlignEquals",
		"AlignDoubleArrow"
	],
	"php55warning": true,
	"php_bin": "/Applications/MAMP/bin/php/php5.6.7/bin/php",
	"psr1": false,
	"psr2": true,
	"version": 3
}

**Comment by dericofilho** [comment]
@rufhausen Thanks for reporting this. I am going to fix it ASAP. For now consider using:

```
"ignore_list":".blade.php",
```

**Comment by dericofilho** [comment]
@rufhausen please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/35ba0d9e6d554f87955abf24b90ebf334a177586 and test.

**Comment by rufhausen** [comment]
@dericofilho Appears to work now with the previous ignore_list format. It also appears to be ignoring .blade.php files as expected.

Thanks.
