### ISSUE TITLE
<?php tag removed

### ISSUE THREAD

**Issue by crimsonvspurple** [dericofilho/sublime-phpfmt#138]
Hi.

I'm not sure if I'm doing something wrong here...pressing CTRL+F11 formats the php code perfectly except the <?php is removed from the start.

I have been using this without any issue since this: https://github.com/dericofilho/sublime-phpfmt/issues/119

Any idea?

Here's the userconfig:

```JSON
{
	"enable_auto_align": true,
	"format_on_save": false,
	"indent_with_space": false,
	"passes":
	[
		"PSR2KeywordsLowerCase",
		"PSR2LnAfterNamespace",
		"PSR2CurlyOpenNextLine",
		"PSR2ModifierVisibilityStaticOrder",
		"PSR2SingleEmptyLineAndStripClosingTag"
	],
	"php_bin": "c:/php/php.exe",
	"psr1": true,
	"psr1_naming": false,
	"psr2": false,
	"smart_linebreak_after_curly": true,
	"version": 3,
	"visibility_order": true,
	"yoda": true
}
```

**Comment by AntyRace** [comment]
Same here.... After last update (yesterday)

**Comment by dericofilho** [comment]
@crimsonvspurple @AntyRace I am sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@crimsonvspurple @AntyRace please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/3.25.0

**Comment by AntyRace** [comment]
Working. Thanks for fast response. :)

**Comment by dericofilho** [comment]
@AntyRace thanks for using the plugin.

**Comment by crimsonvspurple** [comment]
Thank you for fixing this so fast. :)

**Comment by dericofilho** [comment]
@crimsonvspurple thanks for using the plugin. :)
