### ISSUE TITLE
Custom format

### ISSUE THREAD

**Issue by cnzhangxl** [dericofilho/sublime-phpfmt#139]
before:
<?php
for ($i = 0; $i < 10; $i++) {
}

after:
<?php
for($i = 0; $i < 10; $i++)
{
}

"for ($i = 0; $i < 10; $i++) {  "
to
"for($i = 0; $i < 10; $i++)
{"

how can i setting?

**Comment by dericofilho** [comment]
@cnzhangxl please, consider using the option `AllmanStyleBraces` within  `phpfmt: toggle additional transformations`.

**Comment by cnzhangxl** [comment]
thanks @dericofilho,  now i'm use   "laravel_style": true,

**Comment by dericofilho** [comment]
@cnzhangxl, laravel style is deprecated, and will be removed in the next major release. I strongly suggest you use AllmanStyleBraces instead.
