### ISSUE TITLE
I don't wanna convert the space to tab

### ISSUE THREAD

**Issue by gfd6th** [dericofilho/sublime-phpfmt#140]
Hi,
I found phpfmt will format my code from from four spaces to tab when I am saving. But I wanna keep the space. 
I have toggle the "indentation  with spaces" in cmd+shift+p. But I don't see any change in phpfmt user setting.

**Comment by dericofilho** [comment]
@gfd6th I am sorry for this bug. Paste here your configuration file.

**Comment by gfd6th** [comment]
```
{
	"autocomplete": true,
	"autoimport": true,
	"excludes":
	[
		"OrderUseClauses",
		"SortUseNameSpace"
	],
	"laravel_style": true,
	"passes":
	[
	],
	"php55warning": true,
	"php_bin": "/usr/local/bin/php",
	"psr2": true,
	"smart_linebreak_after_curly": true,
	"space_around_exclamation_mark": true,
	"version": 3
}
```

**Comment by dericofilho** [comment]
@gfd6th please, add in your configuration file:
```
"indent_with_space":4,
```

**Comment by gfd6th** [comment]
Thanks for your help.
I mean that there were some 4 spaces indentations in my files before.
They will be formatted to tabs when I am saving the file, Actually I wanna keep 4 spaces coding style.
`"indent_with_space":4` seems useless
```
{
	"autocomplete": true,
	"autoimport": true,
	"excludes":
	[
		"OrderUseClauses",
		"SortUseNameSpace"
	],
	"laravel_style": true,
	"passes":
	[
	],
	"php55warning": true,
	"php_bin": "/usr/local/bin/php",
	"psr2": true,
	"smart_linebreak_after_curly": true,
	"space_around_exclamation_mark": true,
	"version": 3,
	"indent_with_space":4,
}

```

**Comment by dericofilho** [comment]
This json file has a syntax error. Remove the last comma and try again.

**Comment by dericofilho** [comment]
@gfd6th `indent_with_space` is incompatible with `laravel_style`. Please set `laravel_style` to `false` and add `AllmanStyleBraces ` within `passes`.

**Comment by gfd6th** [comment]
That is it. Now I could keep 4 spaces indentation.
Thanks @dericofilho
