### ISSUE TITLE
phpfmt not format on Mac Yosemite (no errors on debug)

### ISSUE THREAD

**Issue by patrickmaciel** [dericofilho/sublime-phpfmt#143]
Hi,

I'm get no errors when try to format my php code.

My settings:

    phpfmt (php version) out:
     PHP 5.6.9 (cli) (built: May 27 2015 22:45:34) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

    phpfmt (php version) err:
     
    phpfmt (fmt.phar version) out:
     
    phpfmt (fmt.phar version) err:
     
    cmd_fmt:  ['/usr/local/bin/php', '-dshort_open_tag=On', '/Users/patrickmacielcampos/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/patrickmacielcampos/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--psr1', '--psr1-naming', '--psr2', '--indent_with_space=4', '--enable_auto_align', '--smart_linebreak_after_curly', '--oracleDB=/Users/patrickmacielcampos/Sites/iab/sac/laravel4x/oracle.sqlite', '-v', '-o=-', '-']
    p:
     0
    err:

User settings:

    {
      "enable_auto_align": true,
      "format_on_save": true,
      "indent_with_space": 4,
      "debug": true,
      "passes":
      [
      ],
      "php_bin": "/usr/local/bin/php",
      "psr1": true,
      "psr2": true,
      "version": 3
    }

Default settings:

    {
    "version": 3,
    "php_bin":"/usr/local/bin/php",
    "format_on_save":true
    }

My unformatted code:

    <?php namespace Admin;

        use BaseController;

    class ReportsController extends BaseController
    {
        public function openTickets()
    {
                $dateStart = Input::get('date_start');
            $dateEnd = Input::get('date_end');

        $data = Report::openTickets($dateStart, $dateEnd);

            return View::make('reports.open_tickets')
                ->with('data', $data);
        }
    }

**Comment by dericofilho** [comment]
@patrickmaciel which version have you had installed?

**Comment by dericofilho** [comment]
@patrickmaciel I cannot reproduce this bug. Please, consider reinstalling the plugin. Also, try to disable the autocomplete for now.

**Comment by patrickmaciel** [comment]
The last version. I upgrade my sublime packages every day.

I'll try to reinstall now.

**Comment by patrickmaciel** [comment]
Works. Thanks.

But I do not know what cause the problem.
