### ISSUE TITLE
Turn off re-ordering of use statements or provide alternative ordering option

### ISSUE THREAD

**Issue by rufhausen** [dericofilho/sublime-phpfmt#145]
I've not been able to to figure out how to disable the re-ordering of use statements in classes. They are currently ordered alphabetically (a-z) which is fine by me. However, others prefer ordering by length of the use statement and that appears to be a common format.
It would be great if phpfmt could re-order based on length as an option, or at least turn off the functionality (I apologize if that's possible now and I just haven't found the config setting), so I'm not always overwriting others' commits unnecessarily.
Thanks!

**Comment by dericofilho** [comment]
@rufhausen It is possible. Please, try to follow the thread https://github.com/dericofilho/sublime-phpfmt/issues/130 if you do not manage to have it working, then we can check for a bug fix.

**Comment by rufhausen** [comment]
"OrderUseClauses" does appear to work for me.
The order by length enhancement would also be cool. :)

Thanks again.

**Comment by dericofilho** [comment]
@rufhausen Hi. sublime-phpfmt actually uses dericofilho/php.tools Have you take a look at it? If you want, you may try to make such option available. I will take PRs gladly.
