### ISSUE TITLE
Bug with AutoSemicolon while using switch case

### ISSUE THREAD

**Issue by simonfranz** [dericofilho/sublime-phpfmt#148]
Hi there,
i'm testing AutoSemicolon and found a bug, where it adds incorrect semicolons.

given this script it adds a semicolon after the case "song": line. I think there shouldn't be inserted a semicolon.

     switch ($object) {
            case "song":
                echo "sounds cool";
                break;
            case "artist":
                echo "sounds nice";
                break;
            case "cd":
                echo "sounds awful";
                break;
            default:
                break;
        }

Thanks for this useful plugin!

best regards

**Comment by dericofilho** [comment]
@simonfranz I am sorry for this bug.  I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@simonfranz Please manually update to https://github.com/dericofilho/sublime-phpfmt/commit/e75864fc377b19bb24bd1e2bd825e6a07a826b00

**Comment by simonfranz** [comment]
dear @dericofilho, i don't think you need to excuse yourself for providing a free plugin. I think it's normal that sometimes there are bugs, especially in betas ;-)
Thanks for the quick fix.

Best Regards
