### ISSUE TITLE
It can't work in WAMP.

### ISSUE THREAD

**Issue by ioriandy4** [dericofilho/sublime-phpfmt#149]
I use sublimte text3 and WAMP. I install sublime-phpfmt but there are no commands when i press ctrl+shitf+p.
![image](https://cloud.githubusercontent.com/assets/7553775/8332721/f80cfe84-1ac1-11e5-8edb-d46b1d3b8294.png)

**Comment by dericofilho** [comment]
@ioriandy4 Please, send your configuration file and console output.

**Comment by ioriandy4** [comment]
@dericofilho 
![image](https://cloud.githubusercontent.com/assets/7553775/8332804/633a30d2-1ac2-11e5-8eaf-c80226c47132.png)

the console:
ImportError: No module named 'sublime-phpfmt-4'
found 10 files for base name Main.sublime-menu
Writing file /E/Sublime Text Build 3062/Data/Packages/User/phpfmt.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/phpfmt.sublime-settings
Writing file /E/Sublime Text Build 3062/Data/Packages/User/phpfmt.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/phpfmt.sublime-settings
Unable to open /E/Sublime Text Build 3062/Data/Packages/phpfmt/phpfmt.sublime-settings

**Comment by dericofilho** [comment]
@ioriandy4 This json file is wrong in many ways. I wonder what has happened to lead you to such state. Please replace your configuration file with:

```
{
"version": 3,
"php_bin": "D:/360yunpan/wamp_home/bin/php/php5.5.12/php.exe",
"php55compat": true
}
```

**Comment by ioriandy4** [comment]
I use the fomat now commands,and can't work.
the console:
phpfmt (php_ver) cmd:
 ['D:/360yunpan/wamp_home/bin/php/php5.5.12/php.exe', '-v']
phpfmt (php_ver) out:
 PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

phpfmt (php_ver) err:
 
error: Null inputs. (diff_main)

**Comment by dericofilho** [comment]
@ioriandy4 Please, paste here the code gist which you are trying to format.

**Comment by ioriandy4** [comment]
```php
<?php
    public function post_thumbnail_src()
    {//Post Thumbnail From caibaojian.com
        global $post;
        if ( $values = get_post_custom_values("thumbnail") ) {
        $values = get_post_custom_values("thumbnail");
        $post_thumbnail_src = $values [0];} elseif ( has_post_thumbnail() ) { //
        $thumbnail_src = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID),'full');
        $post_thumbnail_src = $thumbnail_src [0];
        } else {$post_thumbnail_src = '';
        ob_start();
        ob_end_clean();
        $output = preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $post->post_content, $matches);
        if (!empty($matches[1][0])) {
        $post_thumbnail_src = $matches[1][0]; 
        } else {
        $post_thumbnail_src = get_template_directory_uri().'/images/default_thumb.jpg';
        }
        };
        echo $post_thumbnail_src;
    }
 ?>
```

**Comment by dericofilho** [comment]
@ioriandy4 This code has syntax error. `public` method outside of the scope of a class.

**Comment by ioriandy4** [comment]
It works ! You are so nice!
