### ISSUE TITLE
How to set the keybinds to the commands?

### ISSUE THREAD

**Issue by ioriandy4** [dericofilho/sublime-phpfmt#150]
How to set the keybinds to the commands?Can you show me some example?

**Comment by dericofilho** [comment]
@ioriandy4 Please, look and change the key bindings in `User/Default.sublime-keymap`

**Comment by ioriandy4** [comment]
the key bind can't work:
[
 { "keys": ["ctrl+b","ctrl+f"], "command": "format now" },
]

**Comment by dericofilho** [comment]
@ioriandy4 base yourself on this https://github.com/dericofilho/sublime-phpfmt/blob/master/Default%20(Windows).sublime-keymap

**Comment by ioriandy4** [comment]
OK,thanks!
