### ISSUE TITLE
It change my funciton's name!

### ISSUE THREAD

**Issue by ioriandy4** [dericofilho/sublime-phpfmt#151]
before the fromat:function custom_the_views(){...}

after the format:function customTheViews(){...}

I don't want the format to change my function's name . How to set?

**Comment by dericofilho** [comment]
@ioriandy4 Please, consider disabling PSR1.

**Comment by ioriandy4** [comment]
I have disabled PSR1.But it still change my funciton's name. Is it a bug?

**Comment by dericofilho** [comment]
@ioriandy4 No. It seems you have not done it properly. Please, paste here your configuration file.

**Comment by ioriandy4** [comment]
I check it and change it . It's OK now.
