### ISSUE TITLE
How Can I  do not convert TRUE FALSE NULLto true false null

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#153]
How Can I do not convert TRUE FALSE NULL to true false null
and
 if (!defined('BASEPATH')) exit('No direct script access allowed');
dont convert to
 if (!defined('BASEPATH'))
{
exit('No direct script access allowed');
}

**Comment by dericofilho** [comment]
@adrianceding 

Regarding the lower case conversion, add `PSR2KeywordsLowerCase` to `excludes`

Regarding braces,  currently, they are mandatory to make the formatter to work properly. You cannot help it.
