### ISSUE TITLE
5.6 version

### ISSUE THREAD

**Issue by AntyRace** [dericofilho/sublime-phpfmt#154]
Hi, 
Today on each save i have popup with info to upgrade my php version, but:

✔ 07:59 ~ $ php -v
PHP 5.6.7 (cli) (built: Mar 23 2015 01:51:22) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
✔ 07:59 ~ $ 

Thanks for this tool :)

**Comment by dericofilho** [comment]
@AntyRace be sure to put the correct PHP path in your configuration file (`php_bin`)

**Comment by AntyRace** [comment]
Yep, that's was the problem.... 
I didn't have "php_bin" key in configuration file.
Should plugin check default system path, when there isn't "php_bin" key ?

✔ 07:59 ~ $ which php
/usr/local/bin/php
✔ 08:08 ~ $ 

Regards :)

**Comment by dericofilho** [comment]
@AntyRace In the absence of php_bin, it will defer the PHP binary search to OS's %PATH%/$PATH
