### ISSUE TITLE
Plugin constantly asking for database location for analyzing php code

### ISSUE THREAD

**Issue by David-van-den-Bor** [dericofilho/sublime-phpfmt#155]
There was a issue where the plugin kept asking me for the database location (needed for analyzing PHP code) when I selected "PHPFMT analyze this" from the Sublime text menu. It was related to another issue that I submitted which was resolved. I discovered the reason: **The plugin uses PHP modules it can't find** in your PHP installation, but doesn't give feedback when this happens. I activated the PHP module for **sqlite3.so** in my PHP extensions configuration (in AMPPS) and the problem went away.

![schermafbeelding 2015-06-26 om 11 11 32](https://cloud.githubusercontent.com/assets/5694412/8374537/72fa9b12-1bf6-11e5-9de0-259ea31fcb80.png)

So to anyone having the same issues: turn on the debugging setting in the PHPFMT plugin, like so:

```json
{
	"debug": true
}
```

and use the **Sublime text console** ```ctrl + ` ```  to find out what the plugin error is. The Sublime text console logs every action you do in Sublime, giving you information as to what is going on "behind the curtains". Try to spot the "Fatal error" notifications!

![schermafbeelding 2015-06-26 om 11 46 26](https://cloud.githubusercontent.com/assets/5694412/8374862/0e094480-1bf9-11e5-8ba9-8ebd2e3982c5.png)

The plugin author said that he was working on better error notification in the next version of the plugin, so maybe then there will be some kind of "missing PHP modules" notification :-)

**Comment by dericofilho** [comment]
Thanks for the thorough explanation
