### ISSUE TITLE
Remove auto-Semicolon as an option

### ISSUE THREAD

**Issue by NoMan2000** [dericofilho/sublime-phpfmt#156]
Auto-Semicolon has a bug, (which may have been fixed), but if you have PHP and HTML markup like:

<?php 
if ($someVar) { ?>

}
?>

phpfmt would convert this to:

<?php
if ($someVar) {
;?>

Note the semi-colon after the opening curly brace.  Since this is a beta-feature, there should be some way to disable it or prevent it while it's being tested.

**Comment by dericofilho** [comment]
@NoMan2000 the best way of not using it, is by not activating it. The word "beta" is there for a reason, so people know what they're stepping into. 

I will try to sort out an option in command pallette where beta options can be hidden  or not. I might put this in the next major release. 

Meanwhile, I shall address this issue you just put forward.

**Comment by NoMan2000** [comment]
Awesome, this is a great plugin and I'm glad it's under such active development. 

So newb question, how do I deactivate Auto-semicolon until it's out of beta stage?

**Comment by dericofilho** [comment]
Please, use command pallette with the option to exclude passes. It will be there to be deactivated. It is weird, as AutoSemicolon is not activated by default. Could you please paste here your configuration file?

**Comment by NoMan2000** [comment]
{
	"disable_auto_align": false,
	"autoimport": true,
	"enable_auto_align": false,
	"format_on_save": true,
	"indent_with_space": true,
	"psr1_naming": true,
	"passes":
	[
	],
	"php55warning": false,
	"php_bin": "/usr/local/bin/php",
	"psr1": true,
	"psr2": true,
	"version": 3,
	"autocomplete": true,
	"order_method": true,
	"smart_linebreak_after_curly": true,
	"generate_phpdoc": true
}

**Comment by dericofilho** [comment]
@NoMan2000 please, add this to your configuration file.
```
"excludes":
	[
		"AutoSemicolon"
	],
```

I did not manage to reproduce what you described, with AutoSemicolon deactivated it did not added the extra semicolon by itself. Could you please be more specific regarding configuration, environment, context of piece of code and steps to reproduce this issue?

**Comment by dericofilho** [comment]
@NoMan2000 ping!

**Comment by dericofilho** [comment]
@NoMan2000 Hi, if I do not hear until June 30th, I shall close this issue.

**Comment by NoMan2000** [comment]
I did that, it still adds the semi-colon. It's actually caused by setting the psr1 to true.  With psr1 set to true, it adds the semi-colon, with it set to false, no semi-colon. Example code:

    if ($permissions_user > PermissionsScope::VIEW) {?>
    <form>

        <b><?=$t->gettext($translation->bulkActions);?>: </b>
        <select name="actions" id="actions" size="1">
            <option value="1"><?=$t->gettext($translation->bulkNone);?></option>
            <option value="2"><?=$t->gettext($translation->bulkChangeGroup);?></option>
            <option value="3"><?=$t->gettext($translation->changePolicyGroup);?></option>
            <option value="4"><?=$t->gettext($translation->bulkSendSms);?></option>
        </select>

        <span id="sitebox" name="sitebox" style="display:none;">
        To Group:
            <select name="sites" id="sites" size="1">
            <?=$siteList;?>
            </select>
        </span>

        <span id="groupbox" name="groupbox" style="display:none;">
        To Policy Group:
            <select name="groups" id="groups" size="1">
                <?=$groupList;?>
            </select>
        </span>

        <span id="smsbox" name="smsbox" style="display:none;">
        Custom SMS:
            <textarea name="mysms" id="mysms" cols="55" rows="3"></textarea>
        </span>

        <input type="submit" value="<?=$t->gettext($translation->execute);?>">
    <div id="InfoHolder" class="alert alert-info fade in hide">
        <i class="fa-fw fa fa-info"></i>
        <div id="InfoContent"></div>

    </form>

    <?php
    }
    ?>

**Comment by dericofilho** [comment]
@NoMan2000 OK... so it is really a PSR1 bug. For now, try disabling PSR1OpenTags with 

```
"excludes":
    [
        "PSR1OpenTags"
    ],
```

**Comment by NoMan2000** [comment]
That fixed it, with psr1 enabled.

**Comment by dericofilho** [comment]
@NoMan2000 Nice. The bug is still there, I will release a fix it ASAP.

**Comment by dericofilho** [comment]
@NoMan2000 please, update https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.11.0
