### ISSUE TITLE
AlignDoubleArrow grouped by blank lines

### ISSUE THREAD

**Issue by danwall** [dericofilho/sublime-phpfmt#157]
Thanks for the fantastic project.

I was wondering if it was possible to have `AlignDoubleArrow` act more like `AlignEquals` where it "groups" lines where a blank new line is detected.

For example, in `AlignEquals` we get this:

```php
$short  = 'test';
$short2 = 'test';

$reallylong       = 'test';
$anothereallylong = 'test';
```

In `AlignDoubleArrow` we get this:

```php
$test = [
    'shortkey'      => [
        'shortkey'             => 'test',
        'shortishkey'          => 'test',

        'reallylongkey'        => 'test',
        'anotherreallylongkey' => 'test',
    ],

    'reallylongkey' => [
        'shortkey'             => 'test',
        'shortishkey'          => 'test',

        'reallylongkey'        => 'test',
        'anotherreallylongkey' => 'test',
    ],
];
```

It would be great if we could get something more like this:

```php
$test = [
    'shortkey' => [
        'shortkey'    => 'test',
        'shortishkey' => 'test',

        'reallylongkey'        => 'test',
        'anotherreallylongkey' => 'test',
    ],

    'reallylongkey' => [
        'shortkey'    => 'test',
        'shortishkey' => 'test',

        'reallylongkey'        => 'test',
        'anotherreallylongkey' => 'test',
    ],
];
```

The above example isn't so bad, but when you start building bigger arrays and add comments between each section it starts to get hard to read.

Thanks again.

**Comment by dericofilho** [comment]
@danwall thanks for your suggestion, I think this is a good idea. Do you feel you can produce a PR with this change?

**Comment by danwall** [comment]
@dericofilho after having spent some time with the code I'm not sure that I understand how the formatter works fully so I don't think that I would be able to at this point sorry.

**Comment by dericofilho** [comment]
@danwall I will work on this. It will take a while though. I shall leave this issue open so I can notify you of this change.

**Comment by dericofilho** [comment]
@danwall Please, upgrade to:
https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.10.0

**Comment by danwall** [comment]
@dericofilho Thanks so much for this, it appears to be working exactly as expected on OS X but I'm having some problems on Windows.

I'm thinking that it may be to do with using `PHP_EOL` instead of `$this->newLine`?

https://github.com/dericofilho/php.tools/blob/fa36e1632c5b6fca3b3475df701c1cd203816e59/src/Additionals/AlignGroupDoubleArrow.php#L45

**Comment by dericofilho** [comment]
@danwall you are right, nice catch. I will deploy a fix on it ASAP.

**Comment by dericofilho** [comment]
@danwall please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.12.0

**Comment by danwall** [comment]
Perfect! Thank you.
