### ISSUE TITLE
how to stop phpfmt changing method names

### ISSUE THREAD

**Issue by rajneeshojha** [dericofilho/sublime-phpfmt#158]
HI,
your plugin works very good, but how do i disable it that it does not changes method names
because of this it breaks code in other files which are calling it 
like it changing my function mail_template_form to camel case or any thing which will break things in other files like function names,variables name etc

**Comment by dericofilho** [comment]
@rajneeshojha I am sorry for this inconvenience. Have you considered disabling PSR1?

**Comment by dericofilho** [comment]
@rajneeshojha ping!

**Comment by rajneeshojha** [comment]
this is my config
{
"version": 2,
 "php_bin":"/Applications/MAMP/bin/php/php5.6.7/bin/php",
 "format_on_save":true,
"option": "value",
"psr1":false,
"camelcase":false,
"psr2":false,
"disable_auto_align":false,
"debug":true
}

and this is debug output :
cmd_fmt:  ['/Applications/MAMP/bin/php/php5.6.7/bin/php', '-dshort_open_tag=On', '/Users/rajneesh/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/rajneesh/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--psr1', '--psr1-naming', '--psr2', '--indent_with_space', '--smart_linebreak_after_curly', '-v', '-o=-', '-']
p:
 0
err:
 Used passes: RTrim, EliminateDuplicatedEmptyLines, PSR2IndentWithSpace, LeftAlignComment, PSR2SingleEmptyLineAndStripClosingTag, PSR2ModifierVisibilityStaticOrder, PSR2CurlyOpenNextLine, PSR2LnAfterNamespace, PSR2KeywordsLowerCase, PSR1MethodNames, PSR1ClassNames, PSR1ClassConstants, PSR1BOMMark, PSR1OpenTags, Reindent, ReindentAndAlignObjOps, ReindentIfColonBlocks, ReindentLoopColonBlocks, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine


but still it is converting function mail_template_form to mailTemplateForm

**Comment by dericofilho** [comment]
@rajneeshojha sublime text 2 or 3?

Add this to your configuration file:
```
{
...
	"psr1": false,
	"psr1_naming": false,
	"psr2": false,
...
}
```

**Comment by dericofilho** [comment]
@rajneeshojha This configuration you sent me, is this from the Global configuration or the user configuration?

Could you please, paste both of configuration files here? Indicating which is which

**Comment by rajneeshojha** [comment]
i sent you was global conf
here it is user conf
{
	"disable_auto_align": false,
	"format_on_save": true,
	"indent_with_space": true,
	"passes":
	[
	],
	"php_bin": "/Applications/MAMP/bin/php/php5.6.7/bin/php",
	"psr1": true,
	"psr2": true,
	"version": 3
}

**Comment by dericofilho** [comment]
@rajneeshojha OK. it is exactly what I expected to be. You did not disable PSR properly. Consider adding this to user configuration file.

```
{
...
	"psr1": false,
	"psr1_naming": false,
	"psr2": false,
...
}
```

**Comment by rajneeshojha** [comment]
Excellent sir , it is first time i received that much fast support for any free package 
Thankx again for your hard work

**Comment by dericofilho** [comment]
@rajneeshojha Thanks for using this plugin.
