### ISSUE TITLE
Abstract class formatting

### ISSUE THREAD

**Issue by p1mps** [dericofilho/sublime-phpfmt#159]
Hello,

I have a problem when an abstract class code is formatted by the plugin. Basically the "abstract" keyword is forced to stay before the "class" keyword:

abstract class Foo {

}

becomes

abstract 
class Foo {

}

Is this due to some particular code styling or is it an error?

**Comment by dericofilho** [comment]
@p1mps I am sorry for this bug. I have not managed to reproduce it. I need more context around the code, and both configuration files so I try to reproduce it.

**Comment by p1mps** [comment]
My user setting:

{
	"passes":
	[
	],
	"version": 3
}

My Default Setting
{
	"close_windows_when_empty": true,
	"color_scheme": "Packages/User/SublimeLinter/Flatland Dark (SL).tmTheme",
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "Flatland Dark.sublime-theme",
	"translate_tabs_to_spaces": true
}

I'm on fullscreen, I don't know if it could matter and I'm on Mac OS X.

**Comment by dericofilho** [comment]
@p1mps the default settings you sent are wrong. I need the default settings from the plugin.

Also invoke the option `phpfmt: troubleshoot information` and paste here.

**Comment by p1mps** [comment]
The troubleshoot:

phpfmt (php version):
PHP 5.6.9 (cli) (built: May 15 2015 09:36:14) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

phpfmt (php tokenizer) found

phpfmt (fmt.phar version):
/Users/p1mps/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar 9.2.3

Sorry, the plugin settings:

{
"version": 2,
// "php_bin":"/usr/local/bin/php",
// "format_on_save":true,
"option": "value"
}

**Comment by dericofilho** [comment]
@p1mps with the code snippet you sent, I cannot reproduce the bug. Can you send a bigger code example which actually trigger the error?

**Comment by p1mps** [comment]
<?php

namespace Framework\Database;
use Framework\Database\ModelInterface;
use Framework\Database\Query;

abstract

class Model implements ModelInterface {

	protected static $query;

	protected $data;

	public static function init() {
		if (self::$query === null) {
			self::$query = new Query();
		}
	}

}

Model::init();

**Comment by dericofilho** [comment]
@p1mps I tried to reproduce this problem in many ways. I couldn't. The only situation that happens what you just described is when `abstract` and `class` are already in separated lines. Can you produce a screencast showing step by step how to reproduce the problem starting from an empty file? I am really sorry for asking this, but unless I manage to reproduce the bug, I cannot help it.

**Comment by dericofilho** [comment]
@p1mps ping!

**Comment by p1mps** [comment]
Ok I'll make you a screencast, just give me time :)

**Comment by dericofilho** [comment]
@p1mps ping!

**Comment by p1mps** [comment]
![out](https://cloud.githubusercontent.com/assets/246381/8480179/7a45de78-20dc-11e5-8721-b31d77323d1b.gif)

**Comment by dericofilho** [comment]
@p1mps I see other forces in place. Please, I need you to replicate this problem with the snippet you shared with me before, or share this piece of code you are using.

Also, send me the oracle.sqlite if you are using it. 

And finally, I need to rule out interaction with other plugins. Please, disable all of them except sublime-phpfmt

**Comment by dericofilho** [comment]
@p1mps Ping.

**Comment by p1mps** [comment]
@dericofilho close the issue, it was some incompatibility with another formatter/codeintel plugin
