### ISSUE TITLE
Incorrect multi-line method chaining arrow (->) alignment

### ISSUE THREAD

**Issue by danwall** [dericofilho/sublime-phpfmt#160]
There appears to be an issue when aligning multi-line chained methods where one of the parameters is accessing an object property.

Current output:

```php
public function test()
{
    $one = a()->b()
              ->c();

    $two = a()->b($x->y)
        ->c();
}
```

Expected output:

```php
public function test()
{
    $one = a()->b()
              ->c();

    $two = a()->b($x->y)
              ->c();
}
```

Thanks again for the fantastic project.

**Comment by dericofilho** [comment]
@danwall I am sorry for this inconvenience. Are you using `ReindentAndAlignObjOps` or `ReindentObjOps`?

**Comment by danwall** [comment]
This appears to be related to `ReindentAndAlignObjOps`.

**Comment by dericofilho** [comment]
@danwall it seems a bug. I am going to check this out.

**Comment by dericofilho** [comment]
@danwall please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.13.0

**Comment by danwall** [comment]
@dericofilho Perfect, it is now working as expected. Many thanks.
