### ISSUE TITLE
AddMissingParentheses bug with wrapped object instantiation

### ISSUE THREAD

**Issue by danwall** [dericofilho/sublime-phpfmt#161]
There appears to be a bug with how parentheses are being added when using `AddMissingParentheses`

Input:

```php
$a = new A;
$b = (new B);
$c = (new C)->x;
$d = (new D)->y();
```

Current output:

```php
$a = new A();
$b = (new B)();
$c = (new C)->x();
$d = (new D)->y();
```

Expected output:

```php
$a = new A();
$b = (new B());
$c = (new C())->x;
$d = (new D())->y();
```

Thanks again,
Dan

**Comment by dericofilho** [comment]
@danwall I am sorry for this bug. I shall fix it ASAP.

**Comment by dericofilho** [comment]
@danwall please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.14.0

**Comment by danwall** [comment]
Those changes are now working as expected. Thanks!

I have found a few more cases that are still not working correctly.

Input:

```php
$e = e(new E, new E);
$f = f(new F(new F, new F), new F, new F);
```

Current output:

```php
$e = e(new E, new E());
$f = f(new F(new F, new F()), new F, new F());
```

Expected output:

```php
$e = e(new E(), new E());
$f = f(new F(new F(), new F()), new F(), new F());
```

Maybe the excessive nesting in `$f` is a bit unrealistic but I suspect if `$e` is fixed then `$f` will get fixed as well so it's really just another test case to make sure it's covered fully.

Cheers,
Dan

**Comment by dericofilho** [comment]
@danwall please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/d04061c1a6e07486f6b798a93c9651be5f84d007

**Comment by danwall** [comment]
Looks good. Thanks!

How about this one:

Input:

```php
$g = new G(
    new G,
    new G
);
```

Current output:

```php
$g = new G(
    new G(),
    new G
    ());
```

Expected output:

```php
$g = new G(
    new G(),
    new G()
);
```

I'm not actually having issues with this, just trying to think through all the cases so it's no problem if you don't think that this is worth fixing.

**Comment by dericofilho** [comment]
@danwall All bugs are worth fixing. I am going to check this out ASAP.

**Comment by dericofilho** [comment]
@danwall please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/cb57f48e8f64a54f2f10d886c2e58bc48c4b93bf

**Comment by danwall** [comment]
That looks like it has done it for that case.

I've got a few more now.

Input:

```php
$h = new H(array(new H, new H));
$i = new I([new I, new I]);
$j = new J([
    new J,
    new J,
]);
$k = new K([
    new K,
    new K
]);
```

Current output:

```php
$h = new H(array(new H(), new H()));
$i = new I([new I(), new I]());
$j = new J([
    new J(),
    new J(),
]);
$k = new K([
    new K(),
    new K,
]()
);
```

Expected output:

```php
$h = new H(array(new H(), new H()));
$i = new I([new I(), new I()]);
$j = new J([
    new J(),
    new J(),
]);
$k = new K([
    new K(),
    new K(),
]);
```

Note that the long array syntax in `$h` actually works as well as `$j`, I've just added it here for completeness.

It is possible that with `$k` something weird is happening with the rule that adds the `,` in.

Cheers,
Dan

**Comment by dericofilho** [comment]
@danwall please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/ec9e23eccbeaf7c6c09698fa8eb4df2ab659f1d7

**Comment by danwall** [comment]
@dericofilho Looks good.

I think that is it for issues with this now. I will keep an eye out for any more problems.

Cheers,
Dan
