### ISSUE TITLE
Inconsistent for loop spacing with function calls

### ISSUE THREAD

**Issue by danwall** [dericofilho/sublime-phpfmt#162]
It appears that when a function is used in the condition of a for loop, inconsistent whitespace is being added.

Input:

```php
for ($i = 0; strlen($x) < 10; $i++) {
    //
}
```

Output:

```php
for ($i = 0;strlen($x) < 10; $i++) {
    //
}
```

Expected output:

```php
for ($i = 0; strlen($x) < 10; $i++) {
    //
}
```

Thanks,
Dan

**Comment by dericofilho** [comment]
@danwall Thanks for reporting this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@danwall please upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/64ce90ca89efd763377c840d8d8a93f477a0518d

**Comment by danwall** [comment]
Looks like that's fixed it.

Thank you.
