### ISSUE TITLE
Suggestion: AlignEquals for Constants

### ISSUE THREAD

**Issue by danwall** [dericofilho/sublime-phpfmt#163]
I wonder if it would be useful to be able to have AlignEquals apply to different things in different ways. For example, class constants.

```php
class Test
{
    const SHORT   = 1;
    const LONGER  = 2;
    const LONGEST = 3;

    public function test()
    {
        $short = 'short';
        $longer = 'longer';
        $longest = 'longest';
    }
}
```

Thoughts?

**Comment by dericofilho** [comment]
@danwall I like the idea. But this is more of php.tools issue then sublime-phpfmt issue. Could you please open it there? Do you think you can make a PR of it?

**Comment by danwall** [comment]
Of course. It feels as if most issues really belong there, right?

**Comment by dericofilho** [comment]
Indeed. Here I end up doing more support in configuring the plugin than anything else.

**Comment by dericofilho** [comment]
@danwall BTW, if you enable the alignment it should do what you want. Call `phpfmt: toggle auto align`
