### ISSUE TITLE
bug with AutoSemicolon while using if else 

### ISSUE THREAD

**Issue by friskfly** [dericofilho/sublime-phpfmt#165]
##before
```php
if(a<0)
   echo 200
else {
   echo 300
}
```

##after
```php
if(a<0);
   echo 200;
else {
   echo 300;
}
```
It should't insert semicolon after if expression .

**Comment by dericofilho** [comment]
@friskfly I am sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@friskfly please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.17.0

**Comment by friskfly** [comment]
@dericofilho  it works , thanks.
