### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by adrianceding** [dericofilho/sublime-phpfmt#166]
Code:
<?php
switch (1)
{
	case 1:
		$log_id = "{$this->at_users->FullNameDescribe}{$this->lang_current['logmsg_restore_complete']}";
		if (1)
{
			# code...
		}
		break;
}

Config:
{
	"autocomplete": false,
	"autoimport": true,
	"cakephp_style": false,
	"enable_auto_align": true,
	"excludes":
	[
		"DoubleToSingleQuote",
		"IndentTernaryConditions",
		"PSR2IndentWithSpace",
		"PSR2KeywordsLowerCase"
	],
	"format_on_save": false,
	"indent_with_space": false,
	"laravel_style": false,
	"passes":
	[
		"StripExtraCommaInArray",
		"AlignTypehint",
		"AlignDoubleSlashComments",
		"MergeElseIf",
		"AllmanStyleBraces",
		"EncapsulateNamespaces"
	],
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"readini": true,
	"skip_if_ini_missing": true,
	"smart_linebreak_after_curly": true,
	"space_around_exclamation_mark": true,
	"translate_tabs_to_spaces": false,
	"version": 3,
	"vet": false,
	"visibility_order": false
}

**Comment by dericofilho** [comment]
@adrianceding I am sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@adrianceding please upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/4.24.0

**Comment by dericofilho** [comment]
@adrianceding If I don't hear back until July 15th I shall close this issue.

**Comment by adrianceding** [comment]
solved
