### ISSUE TITLE
Missing space after class name constant

### ISSUE THREAD

**Issue by larsnystrom** [dericofilho/sublime-phpfmt#169]
When formatting this as PSR-2:

    $a = [
        'a' => "hey",
        'hey' => "hey",
        PHP_VERSION => 'hey',
        DateTime::class => 'hey',
    ];

It becomes:

    $a = [
        'a'            => "hey",
        'hey'          => "hey",
        PHP_VERSION    => 'hey',
        DateTime::class=> 'hey',
    ];

It's missing a space after the `::class` constant.

**Comment by larsnystrom** [comment]
Wow, that was the quickest bug fix I've ever seen. The patch works. Thank you!

**Comment by dericofilho** [comment]
@larsnystrom Thanks for using the plugin. :) If you feel like it, please spread the word and star it and dericofilho/php.tools.
