### ISSUE TITLE
As Atom Plugin?

### ISSUE THREAD

**Issue by Dgame** [dericofilho/sublime-phpfmt#170]
Would it be possible to offer this plugin for Atom also? I really miss it in Atom. :)

**Comment by Dgame** [comment]
Would it be ok if I make an Atom Plugin which uses your fmt.pchar?

**Comment by dericofilho** [comment]
@Dgame Hi! I did not take the time to do for Atom. But please, go ahead. If you start it, I commit myself to help you through it. :)

**Comment by Dgame** [comment]
You could help me and tell me how I can activate e.g. the `short array syntax`. Do I need refactor.php for that? I already tried `php refactor.php --short_array --from=test.php --to=test.php` but it doesn't work.

**Comment by dericofilho** [comment]
@Dgame you can reverse engineer this plugin by adding `"debug":true` in the configuration file, and checking the command calls in the console.

With that out of the way, probably what you are looking for is `fmt.phar --passes=ShortArray ...`. Please, open a github account with your plugin, so we transfer this issue from here to there.

**Comment by Dgame** [comment]
I only need to know how I pass the transformations to your plugin. ;) But here it is:
https://github.com/Dgame/atom-php-fmt and the issue: https://github.com/Dgame/atom-php-fmt/issues/1
As soon as I know how I can pass the transformations to your plugin it should work. :)
