### ISSUE TITLE
key binding

### ISSUE THREAD

**Issue by rajneeshojha** [dericofilho/sublime-phpfmt#171]
in my user key binding i put   { "keys": ["f2"], "command": "phpfmt: format now" }
but still phpfmt runs on CMD+S
what to do that it does not run in saving file

**Comment by dericofilho** [comment]
Hi,  consider using the toggle of format on save in command pallette.

**Comment by dericofilho** [comment]
@rajneeshojha more specifically: "phpfmt: toggle format on save" in command pallete.

**Comment by rajneeshojha** [comment]
is it possible to have a key binding for this ?

**Comment by dericofilho** [comment]
@rajneeshojha sure, you can add it through Preferences > Package Settings > phpfmt > Key bidding - User.

```
{ "keys": ["f9"], "command": "toggle", "args": {"option":"format_on_save"} }
```

**Comment by rajneeshojha** [comment]
and if i add      { "keys": ["f2"], "command": "format", "args": {"option":"now"} },it will format no key f2 correct? Regards
Rajneesh Ojha 


     On Thursday, July 23, 2015 12:31 AM, C Cirello <notifications@github.com> wrote:
   

 @rajneeshojha sure, you can add it through Preferences > Package Settings > phpfmt > Key bidding - User.{ "keys": ["f9"], "command": "toggle", "args": {"option":"format_on_save"} }

**Comment by dericofilho** [comment]
No. Depends on your platform, but it is already configured with Ctrl+F11 or F11

**Comment by dericofilho** [comment]
```
{ "keys": ["ctrl+f11"], "command": "fmt_now" }
```

**Comment by rajneeshojha** [comment]
Awesome thankx you 
I think if you post this key combo on you page it will help others for sure; Regards
Rajneesh Ojha 


     On Thursday, July 23, 2015 1:21 AM, C Cirello <notifications@github.com> wrote:
   

 { "keys": ["ctrl+f11"], "command": "fmt_now" }
