### ISSUE TITLE
class format error

### ISSUE THREAD

**Issue by QiiSyhx** [dericofilho/sublime-phpfmt#172]
create a new class
class A{}
class B{function b(){}}
when save the file, we have two class a,like this
class A {

}
class A {

}class B {
    function a() {

    }
}

**Comment by dericofilho** [comment]
@QiiSyhx I am sorry for this inconvenience. I have not managed to reproduce this bug. Could you please, copy here the User configuration file of the plugin?

**Comment by QiiSyhx** [comment]
the full configs below:
{
	"enable_auto_align": true,
	"indent_with_space": 4,
	"passes":
	[
		"OrderMethodAndVisibility",
	],
	"php55warning": false,
	"php_bin": "C:/xampp/php-5.6.10/php.exe",
	"psr1_naming": false,
	"psr2": false,
	"version": 4
}

**Comment by dericofilho** [comment]
@QiiSyhx I managed to reproduce this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment]
@QiiSyhx please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/ef9cf78fb34125cf12f6343d4cd88a29330bd32c

**Comment by QiiSyhx** [comment]
@dericofilho  thank u for your hard working

**Comment by dericofilho** [comment]
@QiiSyhx please confirm that's OK. If so, I should like to close this issue.
