### ISSUE TITLE
report a bug

### ISSUE THREAD

**Issue by lichunqiang** [dericofilho/sublime-phpfmt#175]
```
$this->list = (new Query)->select(['id', 'name'])
     ->where(['sex' => 1])
     ->all();
```
It should be formatted as:

```
$this->list = (new Query)->select(['id', 'name'])
     					 ->where(['sex' => 1])
     					 ->all();
```

**Comment by dericofilho** [comment]
@lichunqiang I cannot reproduce this bug. Could you please share your configuration file?

**Comment by dericofilho** [comment]
@lichunqiang please, manually upgrade to https://github.com/dericofilho/sublime-phpfmt/commit/2dbead073732b25ad5264f4accc0080973dc4343

**Comment by lichunqiang** [comment]
it works
