### ISSUE TITLE
Saving unfolds folded code

### ISSUE THREAD

**Issue by shideon** [dericofilho/sublime-phpfmt#62]
Nice plugin but ran into a snag.

When I have folded code and I save, this plugin will unfold my code. Verified this is only when plugin is enabled. Perhaps this is just default sublime behavior when code is moved around? Not sure.

**Comment by dericofilho** [comment]
@shideon It seems I might have found a way to keep the foldings. Please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/4dcf76538546600ea2e04c2a976b625e80afb936 and test. I should like to have your feedback.

**Comment by dericofilho** [comment]
Fixed by https://github.com/dericofilho/sublime-phpfmt/commit/6ab3a09defda3c814b4dff51bc212353344c3392

**Comment by shideon** [comment]
Hey @dericofilho, thanks! I'll check it out when I got a chance.

**Comment by dericofilho** [comment]
@shideon thanks for the feedback. It is embedded within the release 2.0
