### ISSUE TITLE
Extra comma added in arrays

### ISSUE THREAD

**Issue by JeClemens** [dericofilho/sublime-phpfmt#69]
Adds an extra comma to the last item in an arrays

Example code:
```
$post = [
    "content"     => $content,
    "description" => $description
];
```

Result:
```
$post = [
    "content" => $content,
    "description" => $description,
];
```

**Comment by dericofilho** [comment]
@JeClemens Please manually update to https://github.com/dericofilho/sublime-phpfmt/commit/650d15ed33d82c4e4651785c709af0b18c308cc8 and activate the option `phpfmt: toggle strip extra comma in array`

If it works, I shall make a release.

**Comment by dericofilho** [comment]
@JeClemens thanks for your patience. Version released.

**Comment by ctf0** [comment]
@dericofilho toggling the cmnd doesn't add the prop to the user settings file ,is there a chance u add support for this ,this way its easier to the user to know what is toggled and what is not.

**Comment by dericofilho** [comment]
@ctf0 Internally, ST always update the user configuration file with the extra option after you use it first time. Have you tried using the toggle option and checking the user configuration file later?

**Comment by ctf0** [comment]
yeap ,and nothing got added :(

**Comment by JeClemens** [comment]
I checked and is true. The toggle option doesn't work. Well, it partially works.

I called the toggle command ("phpfmt: toggle strip extra comma in array") through the `ctrl + shift + p` menu.
The option changed in memory (or something like that because it works) but is not changed or added to the user settings file.
But If any other toggle option is called after that, for example toggle "psr2", "psr2" is updated as it should be in the user's setting file and "strip_extra_comma_in_array" is updated too (modified or added).

Is like if the "phpfmt: toggle strip extra comma in array" do not call to a method to update user's setting, but if you call another toggle command it does and the changes are reflected.

**Comment by dericofilho** [comment]
@ctf0 @JeClemens please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/1c722b10eeab30255c303c7653598886e7c1f876 and see if the toggle now updates the configuration file.

**Comment by ctf0** [comment]
fixed.

**Comment by dericofilho** [comment]
released

**Comment by JeClemens** [comment]
Yes, it works :+1:

**Comment by kokokurak** [comment]
Is `strip_extra_comma_in_array` setting supposed to work? It doesn't work for me.

**Comment by ccirello** [comment]
Have you activated it through the command palette?

**Comment by kokokurak** [comment]
@ccirello No, this option is missing in my command palette. I see plenty of phpfmt options, but this one is not there.

**Comment by ccirello** [comment]
So probably you want to enable the additional pass. It has been moved ever since.

**Comment by kokokurak** [comment]
@ccirello You are right - when I added `StripExtraCommaInArray` pass, it strips this extra comma. I'm still confused about this relation between passes and settings.
