### ISSUE TITLE
Getter And Setter.

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#70]
hello again , first Happy New Year.

currently when u generate the getter and setter ,its pushed to the end of the file then the files gets saved.
is there a chance to instead generate them right after the variable and display the auto-save that comes after ?

**Comment by dericofilho** [comment]
@ctf0 Happy New Year!

I am afraid I did not understand what you mean. If I understood you correctly, have you considered using the `phpfmt: order method within classes`?

**Comment by ctf0** [comment]
i don't use `order method within classes` because it sorts the methods alphabetically which with something like laravel ,methods wont have the right order ,also what i meant is
```
protected $uservalidation;
public function create(){}
public function store(){}
```
now when i generate the getter and setter ,i expect
```
protected $uservalidation;
protected function setUservalidation($uservalidation) {}
protected function getUservalidation() {}
public function create(){}
public function store(){}
```
but instead i get 
```
protected $uservalidation;
public function create(){}
public function store(){}
protected function setUservalidation($uservalidation) {}
protected function getUservalidation() {}
```

**Comment by dericofilho** [comment]
@ctf0 I understand the predicament. I will try to fix it ASAP.

**Comment by dericofilho** [comment]
@ctf0 this will require a change in dericofilho/php.tools. It will take a while. I shall keep you updated through this issue https://github.com/dericofilho/php.tools/issues/20.

**Comment by ctf0** [comment]
okey np.

**Comment by dericofilho** [comment]
@ctf0 please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/e431d4f6cc7586d4e866526c31c20ca8469b5c94

You are going to see that in naked classes, the added setters and getters will be put together with the properties.

**Comment by dericofilho** [comment]
If I don't receive a feedback until 09 Jan, I shall close this issue.

**Comment by ctf0** [comment]
its working now except for a couple of notes
- all the setter and getter look the same (go,camelCase,snake)
```
protected $postvalidation;
protected function SetPostvalidation($postvalidation)
{
	$this->postvalidation = $postvalidation;
}

protected function Postvalidation()
{
	return $this->postvalidation;
}
```

- can we add a new line b4 the `SetPostvalidation` ?

**Comment by dericofilho** [comment]
@ctf0 I will check what's happening.

**Comment by dericofilho** [comment]
@ctf0 
> all the setter and getter look the same (go,camelCase,snake)
I could not reproduce this. What exactly steps did you take? When I invoke from `phpfmt: getter and setter (camelCase)` for instance, runs just fine.

> can we add a new line b4 the SetPostvalidation ?
Doing.

**Comment by dericofilho** [comment]
@ctf0 please update to https://github.com/dericofilho/sublime-phpfmt/commit/d5a7e2a0ea75fff587e0a005ffa2a1e2c096c624 and see now if the spacing is correct.

**Comment by ctf0** [comment]
both probs are now fixed ,many many thanx.
