### ISSUE TITLE
Added an extra line after the comment.

### ISSUE THREAD

**Issue by qrasik** [dericofilho/sublime-phpfmt#72]
use \Slim\Slim;

	// after this comment
	$app = new Slim;

Not PSR1, PSR2.

**Comment by dericofilho** [comment]
@qrasik I am sorry for this bug, but I am afraid I did not understand what you meant. Do you want the extra space after the comment or not?

**Comment by dericofilho** [comment]
@qrasik Thanks for waiting and I apologize for taking so long.

Please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/98d4fbc2de9a906815ba56a0b6c503e6a99db777

If it works correctly, I shall then make a release.

**Comment by dericofilho** [comment]
@qrasik please consider upgrading to https://github.com/dericofilho/sublime-phpfmt/releases/tag/1.42.0
