### ISSUE TITLE
New line added after comment

### ISSUE THREAD

**Issue by JeClemens** [dericofilho/sublime-phpfmt#73]
I don't know if is a feature or a bug.

Use a "use" statement does that phpfmt add a new line after the comment bellow it. It doesn't happen if the "use" statement is removed.

Before:
```
<?php

require_once 'config.php';
require_once 'vendor/autoload.php';

use Aws\S3\S3Client;

// Amazon S3
$oAS3 = S3Client::factory(['key' => Config::getAmazonAccessKey(), 'secret' => Config::getAmazonSecretKey()]);

// Get AS3 Bucket
$sBucket = Config::getAmazonBucket();
```
After:
```
<?php

require_once 'config.php';
require_once 'vendor/autoload.php';

use Aws\S3\S3Client;

// Amazon S3

$oAS3 = S3Client::factory(['key' => Config::getAmazonAccessKey(), 'secret' => Config::getAmazonSecretKey()]);

// Get AS3 Bucket
$sBucket = Config::getAmazonBucket();
```

**Comment by JeClemens** [comment]
I just saw this is already reported. :)

https://github.com/dericofilho/sublime-phpfmt/issues/72

**Comment by Rozbo** [comment]
在 2015年1月6日，上午10:05，JeClemens <notifications@github.com> 写道：

**Comment by dericofilho** [comment]
@JeClemens @Rozbo 

Please, manually update to 98d4fbc

If it works correctly, I shall then make a release.

**Comment by dericofilho** [comment]
@JeClemens please consider upgrading to https://github.com/dericofilho/sublime-phpfmt/releases/tag/1.42.0

**Comment by JeClemens** [comment]
@dericofilho

Is fixed. Thank you.
