### ISSUE TITLE
some clarification please.

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#74]
there are some cmnds that i just cant understand what are they for ,could u plz explain what they suppose to do ?
```
toggle php.vet
wrong_constructor_name
save_before_format_now  // the format_on_save works on_post_save or on_post_save_async ,so how this cmnd differ from the other one ?
```

**Comment by dericofilho** [comment]
Hello @ctf0 

- toggle php.vet - this is an experimental feature that runs dericofilho/php.vet on file. It is far from complete yet, but it aims to be a replacement for FB's pfff.
- wrong_constructor_name - it upgrades from PHP 4 constructor style (`class A { function A(){}}`) to PHP 5 style (`class A { function __construct(){}}`).
- save_before_format_now - this option handles an edge case when `format_on_save` is disable and the keyboard shortcut is used to format the file. Command Palette always trigger a save before invoking commands, however the keyboard shortcut does not. This option forces the document to be save before formatting when the manual shortcut is used.

**Comment by ctf0** [comment]
the readme could use some update ,thanx for the headsup.
