### ISSUE TITLE
TypeError in .module files

### ISSUE THREAD

**Issue by mike-anthony** [dericofilho/sublime-phpfmt#75]
If trying to format a PHP file that has the extension `.module`, the following error is thrown:

```
Traceback (most recent call last):
  File "N:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "N:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 721, in run
    dofmt(self, self.view)
  File "N:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\phpfmt\phpfmt.py", line 48, in dofmt
    dirnm, sfn = os.path.split(uri)
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by dericofilho** [comment]
@mike-anthony I am really sorry for this bug. I am going to fix it ASAP. However I need more context. Ideally:
- PHP version
- Sublime Text version
- sublime-phpfmt configuration file
- output from console with the option `debug:true` inside the configuration.

Have you tried the option `phpfmt: format now`?

**Comment by mike-anthony** [comment]
Thanks. :+1: 

I'm running PHP 5.5.11, ST3 3065.

With debug on, I get the message "not a PHP file" (whether I use `format now` or `Ctrl+F11`).

**Comment by dericofilho** [comment]
@mike-anthony OK, it is what I expected to be. 

sublime-phpfmt is targeted at PHP files, however, ST does not offer me any consistent information about the file type. And more importantly, even if I analyzed the file content to check for PHP content, then the formatter would take too long analyzing a file before formatting it, essentially defeating its iterative feeling.

Another important aspect is that wherever you look at PHP documentation, you are going to see they always guide you to associate PHP code with `.php` files first, `.phtml` and `.phps` second, and several `.php` variations such `.php3`, `.php4`, `.php5` etc. See installation guidelines for [Apache 2](http://php.net/manual/en/install.unix.apache2.php), [Apache 1](http://php.net/manual/en/install.unix.apache.php) and [MS-IIS](http://php.net/manual/en/install.windows.iis7.php).

Adding up these two point of views, became clear that this plugin should constrain itself to parse only files ending with `.php`.

Keep in mind also that historically, PHP code not ending with these configured filename extensions, had several problems with security. In 2000's, `.inc` php files, usually holding sensitive data were not being parsed, essentially disclosing its informations. 

Among all major frameworks, they either parse non PHP files, or includable PHP files have a slightly longer suffix like `.inc.php`.

For these reasons, thus, I believe the plugin should not care about files not ending with `.php`. 

Of course, I am always willing to update this plugin if you manage to come up with a solid counter-argument to what I wrote above, or an acceptable alternative solution.

**Comment by mike-anthony** [comment]
I do indeed see the issue at hand. However, I'd like to know why it would take long to analyse the file before sending it off for formatting? Surely it would only mean opening the file, checking for `<?php`, and then continuing?

One comment regarding security. I must say, that this aspect really *is* up to the developer. If he/she gets it wrong, that's their problem. It shouldn't stop people like me from being able to use the plugin for my files. In particular, the framework I'm using at present is highly secure. Granted, it should probably use an extension such as `.module.php`, but that's really just a semantics thing.

I think that it would be a good idea to add an option in config whereby a user can specify additional extensions that he/she uses. For example:

```
"additional_extensions": ["module", "inc"]
```

This would mean that custom extensions can be used, and the plugin doesn't need to analyse/check the file first.

I would not go so far as to allow the plugin to disregard the file-type altogether - that would be asking too much.

**Comment by dericofilho** [comment]
@mike-anthony OK. Thanks for your feedback. I will work to make a support for : 
`"additional_extensions": ["module", "inc"]`

It will a take a bit time to be ready, though. You shall receive updates from this thread.

**Comment by dericofilho** [comment]
> I do indeed see the issue at hand. However, I'd like to know why it would take long to analyse the file before sending it off for formatting? Surely it would only mean opening the file, checking for <?php, and then continuing?

Any file scan is proportional to the file size. The bigger the file, more likely it will take long to analyze it. Suppose I am checking a humongously big SQL dump file. The plugin would need to check the whole file to see if it is or not a PHP file, taking in consideration for instance, PHP snippets within a valid SQL string, which can complicate the analysis even further.

**Comment by dericofilho** [comment]
@mike-anthony please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/34cf47fa0e8595e8df728f6055937f3e9810f4bf

And update your configuration file with: 
`"additional_extensions": ["module", "inc"]`

I am going to wait for your feedback before releasing a version with this improvement.

**Comment by mike-anthony** [comment]
Confirmed, works like a charm. Thank you! :+1:
