### ISSUE TITLE
Bug in Laravel's Allman Braces Style

### ISSUE THREAD

**Issue by dericofilho** [dericofilho/sublime-phpfmt#76]
Refer to #71

**Comment by dericofilho** [comment]
Supposedly solved at https://github.com/dericofilho/sublime-phpfmt/commit/e850ff53e5aedc7b0dc841288a87272c484f6edb

Waiting for users feedback @ctf0

**Comment by ctf0** [comment]
will test and come back to u asap.

**Comment by ctf0** [comment]
its fixed but another has surfaced ,if the code have a comment on the line b4 it will be indented.
```
// get the poll choices
$choice = $db->prepare("SELECT * FROM polls_choices WHERE poll_id = $id");
```
after cmnd
```
// get the poll choices
				$choice = $db->prepare();
```
sometimes its indented with 1 tab & sometimes it will be 2 like above

**Comment by dericofilho** [comment]
@ctf0 thanks for the feedback - let's try to stabilize Laravel thoroughly. I would like to ask you to be very patient, because stabilizing Laravel was not really on top of my list.

I will try to fix this ASAP.

**Comment by ctf0** [comment]
its totally fine ,no prob ,to be honest when i use laravel aka,classes and methods everything work without any probs ,this only surface when i use a plain old php ,anyway here are more code as the above wont be very helpful 
```php
<?php

require_once 'init.php';

$id   = $_GET['poll'];
$user = $_SESSION['user_id'];

if (!isset($id))
{
	header('Location: index.php');
}
else
{
	// get the poll info
		$poll = $db->prepare();
	$poll->execute();
	$po = $poll->fetchObject();

	// check if the user has voted for that poll already or not
		$answer = $db->prepare();
	$answer->execute();

	$completed = $answer->rowCount() ? true : false;

	if ($completed)
	{
		$percent = $db->prepare();
		while ($row = $percent->fetchObject())
		{
			$answers[] = $row;
		};
	}
	else
	{
		// get the poll choices
				$choice = $db->prepare("SELECT * FROM polls_choices WHERE poll_id = $id");
		$choice->execute();
		$ch = $choice->fetchAll();
	}
}
```

**Comment by dericofilho** [comment]
@ctf0 please, update to bb56dec9f4b128ed4c675d3301ea9e85b90ca399

I am going to wait for your feedback before closing this issue.

**Comment by ctf0** [comment]
hey again ,sorry no go.

**Comment by dericofilho** [comment]
Could you provide more examples?

**Comment by ctf0** [comment]
i double checked ,the indentation is fixed but any empty lines between the comment and the code is removed.

**Comment by dericofilho** [comment]
OK. I will work on that.

**Comment by dericofilho** [comment]
Please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/087f107b2ea832fcf82119016bdaf6ad826dd2d4

**Comment by ctf0** [comment]
most are fixed but now
this
```
/* post->scopeSearch */
	public function posts()
```
become
```
/* post->scopeSearch */public function posts()
```

**Comment by dericofilho** [comment]
@ctf0 thanks for the feed back... I am going to fix this case. As I said, it will take a while to stabilize Laravel support.

**Comment by piengeng** [comment]
comment line 6352 of fmt.stub.php, "$source = $this->ltrimWhitespaces($source);" seems to solve 
```
/* post->scopeSearch */public function posts()
```
Not sure if this will help as i cannot fully understand the fmt.stub.php :)

**Comment by dericofilho** [comment]
@piengeng Hi! I appreciate your involvement. Please, consider updating LaravelStyle.php in `Additionals/` and using `php build.php` to generate both `fmt.php` and `fmt.phar`

**Comment by dericofilho** [comment]
@ctf0 please, update to https://github.com/dericofilho/sublime-phpfmt/commit/d5e6bf6b3a671e1101193d43301556429058676a 

I believe now it is fixed this issue.

@piengeng please, do the same.

**Comment by ctf0** [comment]
dam i missed this ,thanx its now fixed.

**Comment by dericofilho** [comment]
@ctf0 thanks for the whole patience. closing this and issuing a release.

**Comment by ctf0** [comment]
i hate to open this again but plz check the below
```
Event::listen('send_activation', function ($user)
{

	Mail::send(
		'emails.confirm',
		[
			'username' => $user->username,
			'link'     => $user->code
		],
		function ($send) use ($user)
	{
			$send->to($user->email, $user->username)->subject('activation email');
		}
	);

});
```

**Comment by dericofilho** [comment]
@ctf0 I am really sorry for this bug. I am going to check this ASAP. Please, open a new issue with it.
