### ISSUE TITLE
laravel blade support.

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#77]
i know its kinda out of the main scope ,but is there any slight chance u could add support for this language ???

it basicly a combination between php & html.
![test](https://cloud.githubusercontent.com/assets/7388088/5722639/915c3db2-9b46-11e4-80a4-6c8fe313786b.jpg)

all am after is formating any thing inside the `{{ ... }}`

**Comment by dericofilho** [comment]
@ctf0 Unfortunately no. It is not on the scope of this project. I do not rule out this idea completely. But surely, not now.
