### ISSUE TITLE
php files with html get broken

### ISSUE THREAD

**Issue by jclappiway** [dericofilho/sublime-phpfmt#78]
Indentation get broken on view files (.php containing html and php)

for example :
```
<table>
  <tr>
    <td>
      <h1>
<?php echo 'somethin'?>
</h1>
    </td>
    <td>
<?= 'another' ?>
</td>
  </tr>
</table>
```

**Comment by dericofilho** [comment]
@jclappiway I am really sorry for this bug. I am going to investigate this and fix it ASAP.

**Comment by jclappiway** [comment]
Thanks a lot :+1:

**Comment by dericofilho** [comment]
@jclappiway please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/0cb8b4832c21ef501990321a75ff54c026e484a8 
I want your feedback before closing this issue.

**Comment by jclappiway** [comment]
@dericofilho : it's much better! Thanks and nice work
