### ISSUE TITLE
Laravel Formatting Bug

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#79]
```
Event::listen('send_activation', function ($user)
{

	Mail::send(
		'emails.confirm',
		[
			'username' => $user->username,
			'link'     => $user->code
		],
		function ($send) use ($user)
	{
			$send->to($user->email, $user->username)->subject('activation email');
		}
	);

});
```

https://github.com/dericofilho/sublime-phpfmt/issues/76

**Comment by dericofilho** [comment]
@ctf0 Please update to https://github.com/dericofilho/sublime-phpfmt/commit/37a53e43a9c3b85e10c4669c804769eda696c888

I will wait for your feedback before closing this issue.

**Comment by ctf0** [comment]
the above is fixed but another
```
Event::listen('remove',
	function ()
{
		(new ABC)->remove();
	}
);
```

**Comment by dericofilho** [comment]
@ctf0 Thanks for the feedb.ack. I am going to check this ASAP.

**Comment by dericofilho** [comment]
@ctf0 please, update to https://github.com/dericofilho/sublime-phpfmt/commit/c25334c6076ba5c9e3d1d62af7028a4662eda18c

**Comment by ctf0** [comment]
no go :(

**Comment by dericofilho** [comment]
@ctf0 Please be patient, I am working on that still.

**Comment by dericofilho** [comment]
@ctf0 
I tested this case especifically with https://github.com/dericofilho/sublime-phpfmt/commit/4f1b3d324f6b203e4b42271774418e57f28da6a4.

Please update to https://github.com/dericofilho/sublime-phpfmt/commit/4f1b3d324f6b203e4b42271774418e57f28da6a4

**Comment by ctf0** [comment]
now it add more spaces ,check
```
Event::listen('add_subscribe',

	

function($user)
	{
		(new MailChimp)->add_subscribe($user);
	}
);

Event::listen('update_subscribe',
	function($old_email, $new_email, $user)
	{
		(new MailChimp)->update_subscribe($old_email, $new_email, $user);
	}
);
```
btw i don't know why exactly the first function always get the new lines ,but the 2nd doesn't.

**Comment by dericofilho** [comment]
@ctf0 do you have the original code for this bug?

**Comment by dericofilho** [comment]
@ctf0 Please, also paste here the console log - I am starting to think that it is some misinteraction between passes.

**Comment by dericofilho** [comment]
@ctf0 please, update to https://github.com/dericofilho/sublime-phpfmt/commit/9a152e66dd03a963b1c12bf45a2b69571dbff49b

**Comment by ctf0** [comment]
same as b4 ,here is the full code
```
<?php

use Acme\Mailers\MailChimp;

Event::listen('add_subscribe',

	function ($user) {
		(new MailChimp)->add_subscribe($user);
	}
);

Event::listen('update_subscribe',
	function ($old_email, $new_email, $user) {
		(new MailChimp)->update_subscribe($old_email, $new_email, $user);
	}
);

Event::listen('remove_subscribe',
	function () {
		(new MailChimp)->remove_subscribe();
	}
);
```

**Comment by dericofilho** [comment]
@ctf0 could please provide me with the log from sublime? I guess it might be some misinteraction between passes.

**Comment by ctf0** [comment]
- the console 
```
phpfmt (oracle file): not found
phpfmt: /Laravel/app/Acme/EventHandlers/NewsNotification.php
phpfmt (php version) out:
 PHP 5.6.4 (cli) (built: Dec 27 2014 14:48:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

phpfmt (php version) err:
 
cmd_fmt:  ['php', '/Users/Novo/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=/Users/Novo/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--enable_auto_align', '--visibility_order', '--smart_linebreak_after_curly', '--laravel', '--passes=ShortArray,MergeElseIf,RemoveUseLeadingSlash,PSR2LnAfterNamespace,StripExtraCommaInArray,AlignTypehint', '--prepasses=PrettyPrintDocBlocks,SpaceBetweenMethods', '/Laravel/app/Acme/EventHandlers/NewsNotification.php']
err:
 Formatting ...
.
 1 files total
Took 0.01s
```

- fmt settings
```
{
    "add_missing_parentheses": false,
    "comment_auto_align": false,
    "debug": false,
    "enable_auto_align": true,
    "format_on_save": false,
    "indent_with_space": false,
    "laravel_style": true,
    "linebreak_after_namespace": true,
    "linebreak_between_methods": true,
    "merge_else_if": true,
    "pretty_print_doc_blocks": true,
    "remove_leading_slash": true,
    "short_array": true,
    "smart_linebreak_after_curly": true,
    "strip_extra_comma_in_array": true,
    "typehint_auto_align": true,
    "visibility_order": true
}
```

**Comment by dericofilho** [comment]
@ctf0 please, update to https://github.com/dericofilho/sublime-phpfmt/commit/074d22c166c38db2f9e8796264231ce01f81a38a

As I expected it was a misinteraction between passes.

**Comment by ctf0** [comment]
nice
check this
```
Event::listen('update_subscribe', function($old_email, $new_email, $user)
{
	(new MailChimp)->update_subscribe($old_email, $new_email, $user);
}
);
```
shouldn't it be like
```
Event::listen('update_subscribe', function($old_email, $new_email, $user)
    {
	(new MailChimp)->update_subscribe($old_email, $new_email, $user);
    }
);
```

**Comment by dericofilho** [comment]
@ctf0 To be honest, I have no idea. I am not used to the edge cases of Allman-style... I guess in this particular case the first is right. The extra indentation would exist if there was a linebreak before T_FUNCTION, because then the indentation would not be implicit... But again, I am not sure of this. Let's let Laravel flag to rest a bit - wait for more cases before introducing more changes.
What you say?

**Comment by ctf0** [comment]
okey ,fair enough ,thanx for all ur hard work :metal:
