### ISSUE TITLE
Extra comma in the end of short arrays. as Optional

### ISSUE THREAD

**Issue by agarzon** [dericofilho/sublime-phpfmt#80]
Hi.

It is possible to set the "extra comma in the end of short arrays." as optional?

**Comment by dericofilho** [comment]
@di

**Comment by dericofilho** [comment]
@agarzon hi, I am sorry for this inconvenience. Have you tried using the option "phpfmt: toggle strip extra comma in array"?

**Comment by agarzon** [comment]
Ohh, my bad... I didn't saw that toggle.
Thank you.

**Comment by dericofilho** [comment]
@agarzon No problem. Glad to have helped. :)
