### ISSUE TITLE
Not working with some options

### ISSUE THREAD

**Issue by eclemens-mc** [dericofilho/sublime-phpfmt#81]
For some reason, if I enable the `indent_with_space` this plugin stop working.
It only write and reload the file without modifications.

This is my config file, it works if I toggle `indent_with_space` to `false`
```
{
	"enable_auto_align": true,
	"format_on_save": false,
	"indent_with_space": true,
	"psr2": true,
	"short_array": true,
	"strip_extra_comma_in_array": true,
	"version": 1
}
```

**Comment by dericofilho** [comment]
@eclemens-mc I am really sorry for this bug. I am going to fix it ASAP.

Please, add the option : 
```
"debug": true,
```

And copy into this issue the messages from console.

**Comment by dericofilho** [comment]
@eclemens-mc Please, update to https://github.com/dericofilho/sublime-phpfmt/releases/tag/1.60.0

I will wait your feedback before closing this issue.

**Comment by eclemens-mc** [comment]
Tested, it works. :+1:
