### ISSUE TITLE
extra space inside round braces.

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#82]
hi there ,long time no see :) ,anyway
this
```
if (!isset($id))
{
	header('Location: index.php');
}
```
become
```
if ( ! isset($id))
{
	header('Location: index.php');
}
```

**Comment by dericofilho** [comment]
@ctf0 I am really sorry for this inconvenience. It turns out that this is a Laravel standard (Laravel style implicitly defines whitespaces around "!"). 

I shall add a toggle option to disable this ASAP.

**Comment by ctf0** [comment]
sweet :).

**Comment by dericofilho** [comment]
@ctf0 please manually update to https://github.com/dericofilho/sublime-phpfmt/commit/5a2b78f3c82aa7fa4e8485ed8f8e111111d8bb75

And check the option: "phpfmt: toggle space around exclamation mark"

I will wait your feedback before issuing a release and closing this issue.

**Comment by ctf0** [comment]
nice ,its fixed ,thanx.
