### ISSUE TITLE
Keeping options in sync

### ISSUE THREAD

**Issue by amenadiel** [dericofilho/sublime-phpfmt#84]
First of all: wonderful plugin, it is several order of magnitude above any other php beautifier I've seen.

My only comment is regarding the persistence of options. You reccomend using the Ctrl+Shift+P panel to toggle options, but I've seen that these options do not reflect in phpfmp.sublime-settings, so I'm not able to see what's on and what's off.

If there's any other way to check my current settings, please advise.

**Comment by dericofilho** [comment]
@amenadiel I am really sorry for this bug. Every once in a while I mess up with the configuration persistence. Which are the options that are not persisting? Which is the Sublime Text version you are using?

Could you please confirm to me which is the plugin version you have installed?

**Comment by amenadiel** [comment]
It's version 1.62.0

I'm on Sublime 3 build 3065.

**Comment by dericofilho** [comment]
> Which are the options that are not persisting?

Please?

**Comment by amenadiel** [comment]
I'm sorry. It seems it DOES persist options. For some reason, the first time I installed it I kept open the settings file and it didn't reflect changes, but now it does.

**Comment by dericofilho** [comment]
@amenadiel OK! Glad that it is working.
