### ISSUE TITLE
Weird bug when formatting Dice DI Container

### ISSUE THREAD

**Issue by qooob** [dericofilho/sublime-phpfmt#85]
I just discovered a bug when formatting [Dice](https://github.com/TomBZombie/Dice). You can test it your self. After formatting is applied, it start to return an issue. More details here: https://github.com/TomBZombie/Dice/issues/40

**Comment by TomBZombie** [comment]
To elaborate, it converts a property called $instanceOf to lowercase. I assume it is assuming it's the `instanceof` operator. Should be a simple fix, only lowercase `instanceof` operators if they are preceded by whitespace.

**Comment by qooob** [comment]
Yes, that's it!

**Comment by dericofilho** [comment]
@qooob @TomBZombie I am really sorry for this bug. And I am going to fix it ASAP.

@qooob Please, copy here your configuration file so I can reproduce the bug.

**Comment by qooob** [comment]
To reproduce it just please use [Dice](https://raw.githubusercontent.com/TomBZombie/Dice/master/Dice.php)

**Comment by dericofilho** [comment]
@qooob I just tested Dice and it did not triggered the error with my configuration. Please, copy here your configuration file so I can reproduce the bug.

**Comment by qooob** [comment]
Sure, here:

```
{
	"enable_auto_align": true,
	"format_on_save": false,
	"indent_with_space": true,
	"php_bin": "/usr/bin/php",
	"psr1": false,
	"psr1_and_2": false,
	"psr2": true,
	"version": 1
}

```

**Comment by dericofilho** [comment]
@qooob please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/887c56e153644a72ee8d2810d481b01e04891df8

I should like to have your feedback before issuing a release.

**Comment by qooob** [comment]
@dericofilho Please be kind testing it yourself, I'm out for a while.. Might take could of days. It's an easy thing to do.. ;)
