### ISSUE TITLE
Please continue writing release notes

### ISSUE THREAD

**Issue by leonklingele** [dericofilho/sublime-phpfmt#86]
I've noticed that there were no release notes for the last few updates of 'sublime-phpfmt'.
It was always a pleasure for me to read them :)

Is there a reason why you no longer publish them?

**Comment by dericofilho** [comment]
@leonklingele I have no good reason except that I forget to write them. :) I will keep attention to this.

**Comment by leonklingele** [comment]
Ok, thanks for the heads-up! :heart_eyes_cat:
