### ISSUE TITLE
arrow mis-align

### ISSUE THREAD

**Issue by ctf0** [dericofilho/sublime-phpfmt#88]
this
```
public function save()
	{
		return Image::make($this->temp_path)
		                        ->save($this->save_path.$this->save_name)
		                                    ->widen(600)
		                                    ->greyscale()
		                                    ->save($this->save_path.$this->resize);
	}
```
should be
```
public function save()
	{
		return Image::make($this->temp_path)
                    ->save($this->save_path.$this->save_name)
                    ->widen(600)
                    ->greyscale()
                    ->save($this->save_path.$this->resize);
	}
```

**Comment by dericofilho** [comment]
@ctf0 I am really sorry for this bug, and I am going to fix it ASAP. Is the Laravel style activated?

**Comment by dericofilho** [comment]
@ctf0 please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/d591c34d51c21e72dab4121ed13ae1b4272f2ad6

I will wait for your feedback before closing this issue.

**Comment by ctf0** [comment]
its fixed ,thanx but currently
```
public function save()
	{
		return Image::make($this->temp_path)
			->save($this->save_path.$this->save_name)
			->widen(600)
			->greyscale()
			->save($this->save_path.$this->resize);
	}
```
can we give it 1 more level of indentation like 
```
public function save()
	{
		return Image::make($this->temp_path)
				->save($this->save_path.$this->save_name)
				->widen(600)
				->greyscale()
				->save($this->save_path.$this->resize);
	}
```
or would it break somthing else ?

**Comment by dericofilho** [comment]
@ctf0 you feel the need of an extra indentation because your first line is too long. But in terms of behavior correctness, one indentation deep is the right thing to do.

I plan to replace all these indentation things with some sort of tabwriter. But it is something for the future.

**Comment by ctf0** [comment]
fair enough ,thanx :).
