### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by npulidom** [dericofilho/sublime-phpfmt#90]
The parser finds a syntax error when a const array cames up (PHP 5.6). For example:
```php
Users::ACCOUNT_FLAGS['enabled']
```

**Comment by dericofilho** [comment]
@npulidom I am really sorry for this inconvenience. Are you sure you are running PHP 5.6 in your ST machine? It turns out that you need to be using a certain PHP version to format a same version or older code. Syntax error is returned by PHP binary itself, and the plugin just forward to the user.

**Comment by dericofilho** [comment]
@npulidom please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/be6023ea46cb7cad6dd465692af1386ac119f63a and test.

**Comment by npulidom** [comment]
thanks @dericofilho :)
