### ISSUE TITLE
OR'ing constants

### ISSUE THREAD

**Issue by leonklingele** [dericofilho/sublime-phpfmt#91]
When OR'ing constants using the bitwise operator `|` phpfmt removes spaces before and after this operator.
How it's currently done: `JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES`
How it should be done: `JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES`

**Comment by dericofilho** [comment]
@leonklingele I am really sorry for this bug. I shall fix it ASAP.

**Comment by dericofilho** [comment]
@leonklingele please, upgrade to https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.0.2

**Comment by dericofilho** [comment]
@leonklingele I will wait for your feedback before closing this issue.

**Comment by leonklingele** [comment]
Thank you :)
