### ISSUE TITLE
Avoid braces new line for empty blocks

### ISSUE THREAD

**Issue by eclemens** [dericofilho/sublime-phpfmt#93]
I use PSR-2 formatting that adds a new line before function's braces
```
public static function get($id)
{
...
}
```

I want to request (if doesn't exist) an option to avoid new line for empty functions
```
protected function __construct() {}
```

Currently that is converted to
```
protected function __construct()
{}
```

Thanks this fantastic plugin and your time :+1:

**Comment by dericofilho** [comment]
@eclemens I am sorry for this inconvenience. I shall provide a toggle for such an option as soon as possible.

**Comment by dericofilho** [comment]
@eclemens Please, update to https://github.com/dericofilho/sublime-phpfmt/commit/a3db64a2cf41d6585067eea670ee3946e8f0d7f4
And add `PSR2EmptyFunction` to the passes array within configuration file.

**Comment by eclemens** [comment]
First try didn't work, suppose I did something wrong with the update, but I tried again.

It works :)

**Comment by dericofilho** [comment]
released
