### ISSUE TITLE
Shouldn't modify commented code

### ISSUE THREAD

**Issue by eclemens** [dericofilho/sublime-phpfmt#94]
It is modifying the code between comment tags. It should keep comments without modify. At least no PHPDoc comments. It align all to the left and adds a space before the closing tag.

Example:
```
<?php
function tpl_function_checkForJs($params, &$smarty)
{
    /*
    if ($params) {
        error_log($params);
    }
    */

    check_for_js();
}
```
converts to
```
<?php
function tpl_function_checkForJs($params, &$smarty)
{
    /*
    if ($params) {
    error_log($params);
    }
     */

    check_for_js();
}
```

As always, thanks for your work and time. :smile:

**Comment by dericofilho** [comment]
@eclemens I am really sorry for this inconvenience. Have you considered using "RestoreComments" pass in your configuration file? It is meant to preserve the comments.

```
...
"passes":
	[
		"RestoreComments",
		...
	],
...
```

**Comment by dericofilho** [comment]
@eclemens Also refer to this issue https://github.com/dericofilho/sublime-phpfmt/issues/87

**Comment by eclemens** [comment]
Thank you very much!

Yes, it does what I need.

I didn't know about the "passes" option setting. I'll read again all the documentation.

Thanks.

**Comment by dericofilho** [comment]
Thanks for using the plugin.
