### ISSUE TITLE
Add missing parentheses bug

### ISSUE THREAD

**Issue by eclemens** [dericofilho/sublime-phpfmt#95]
The option "AddMissingParentheses" has a bug when the new instance has parameters

Example:
```
$x = new Number(true);
$y = new Number('hello', true);
```
Becomes:
```
$x = new Numbertrue);
$y = new Number'hello', true);
```

Thanks for all :smile:

**Comment by eclemens** [comment]
And breaks after code format
```
<?php
function test()
{
    $x = new Number('hello', true);

    check_for_js();
}
```
```
<?php
function test()
{
    $x = new Number'hello', true);

check_for_js();
}
```
```
```

**Comment by dericofilho** [comment]
@eclemens I am really sorry for this bug. I shall fix it ASAP.

**Comment by dericofilho** [comment]
@eclemens please, update manually to https://github.com/dericofilho/sublime-phpfmt/commit/ec031812cae6c3e12cf7d0ed8f38e5b832fab8c2

I shall wait for your feedback before closing this issue.

**Comment by eclemens** [comment]
It fixed the problem :+1:
