### ISSUE TITLE
phpfmt deletes my code

### ISSUE THREAD

**Issue by shkurata** [dericofilho/sublime-phpfmt#98]
Hello, 
Today I noticed that on saving phpfmt deleted a line of code from my php file. This is the line:
"use Illuminate\Http\Request;"
What is the reason?

**Comment by dericofilho** [comment]
@shkurata I am sorry for this inconvenience. This is working as intended. Internally, sublime-phpfmt uses  php.tools which provides automatic addition of import calls (`use ...`). Also, it looks to sanitize the code - therefore removing non used imports from the file.

Thus, if you want that sublime-phpfmt keeps on top of your file `use Illuminate\Http\Request;` you must have at least one reference to this dependency in the source code, either as instancing (`new Request()`), or static calling (`Request::foo()`), or static referencing (`Request::$var`) or even in a docblock (`/** @var Request $name`).

If after you made such change this line is still going away, then you might have found a bug, and a gist of source code will be necessary to reproduce the bug.

**Comment by shkurata** [comment]
Thank you. I am just starting with Laravel and it is a little confusing for me, but maybe I learn the class structure better this way :).
