### ISSUE TITLE
multiline method chaining alignment with psr2

### ISSUE THREAD

**Issue by l0c0luke** [dericofilho/sublime-phpfmt#99]
is this a setting I am missing because when I save my file and it auto indents/aligns everything, my PSR2 checkstyle is failing.

what is happening now after save that I do not want. notice it is indenting 5 spaces instead of the required 4.
```
$this->methodName()
     ->secondMethod()
     ->thirdMethod();
```

what I would expect is
```
$this->methodName()
    ->secondMethod()
    ->thirdMethod();
```

**Comment by dericofilho** [comment]
@l0c0luke I am really sorry for this inconvenience. The alignment toggle, when turned off, should not align the way it is aligning now. I am going to fix it ASAP.

**Comment by l0c0luke** [comment]
while your in there this was another one i found after the format seemed to be because of the array in the param...

```
$this->app['scheduler'] = $this->getMockBuilder('somestring')
             ->setConstructorArgs(array($this->app))
                                             ->setMethods(array('getCurrentLongIp'))
                                             ->getMock();
```

**Comment by dericofilho** [comment]
@l0c0luke ok! I will address both cases.

**Comment by dericofilho** [comment]
@l0c0luke please, update https://github.com/dericofilho/sublime-phpfmt/commit/9adb6f6b96725cc1212e0e04ce1ec3543972da6e and add this option in your configuration file. See if your problem is solved.

```
	"passes":
	[
		...        
		"ReindentObjOps",
		...
	],
```

**Comment by l0c0luke** [comment]
i updated through sublime via "update package", i added that option under
passes but I am not seeing any difference. Did I update correctly?

On Mon, Mar 9, 2015 at 1:10 PM, C Cirello <notifications@github.com> wrote:

> @l0c0luke <https://github.com/l0c0luke> please, update 9adb6f6
> <https://github.com/dericofilho/sublime-phpfmt/commit/9adb6f6b96725cc1212e0e04ce1ec3543972da6e>
> and add this option in your configuration file. See if your problem is
> solved.
>
>     "passes":
>     [
>         ...
>         "ReindentObjOps",
>         ...
>     ],
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/99#issuecomment-77931762>
> .
>



-- 

Luke Ollett

+1(949) 371-5292

**Comment by dericofilho** [comment]
No. You have to update manually, it means download the plugin from github directly into plugin directory inside ST.

**Comment by l0c0luke** [comment]
ok, replaced that file. shut down sublime. reopened it. not seeing any differences. here is my user prefs

```
{
	"enable_auto_align": true,
	"format_on_save": true,
	"passes":
	[
		"AlignTypehint",
		"StripExtraCommaInArray",
		"ReindentObjOps"
	],
	"psr2": true,
	"version": 2
}
```

**Comment by dericofilho** [comment]
Ok, i am going to dig deeper

**Comment by l0c0luke** [comment]
these are the lines i am testing on...

```
$this->app['string.string'] = $this->getMockBuilder(
                 '\path\to\class'
             )
             ->disableOriginalConstructor()
             ->getMock();
```

**Comment by l0c0luke** [comment]
as well as 

```
$this->app['captcha']->expects($this->any())
             ->method('check')
             ->will($this->returnValue(1));
```

**Comment by l0c0luke** [comment]
and this one ...

```
$this->app['scheduler'] = $this->getMockBuilder('\path\to\class')
             ->setConstructorArgs(array($this->app))
                                             ->setMethods(array('getCurrentLongIp'))
                                             ->getMock();
```

**Comment by dericofilho** [comment]
I tested these cases and I got:

![image](https://cloud.githubusercontent.com/assets/138827/6564367/435a946e-c6a8-11e4-8b05-1c7a63dcd44c.png)

With:
![image](https://cloud.githubusercontent.com/assets/138827/6564379/4f8902de-c6a8-11e4-98f9-5b2938338259.png)

Please, try updating to (2.6.0)[https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.6.0]

**Comment by l0c0luke** [comment]
seems to work when i set enable_auto_align to false. would be nice to have
but i can live without for now.

On Mon, Mar 9, 2015 at 2:05 PM, C Cirello <notifications@github.com> wrote:

> I tested these cases and I got:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/138827/6564367/435a946e-c6a8-11e4-8b05-1c7a63dcd44c.png>
>
> With:
> [image: image]
> <https://cloud.githubusercontent.com/assets/138827/6564379/4f8902de-c6a8-11e4-98f9-5b2938338259.png>
>
> Please, try updating to (2.6.0)[
> https://github.com/dericofilho/sublime-phpfmt/releases/tag/2.6.0]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/99#issuecomment-77942446>
> .
>



-- 

Luke Ollett

+1(949) 371-5292

**Comment by dericofilho** [comment]
@l0c0luke makes sense - you wanted the alignment to be removed first place right? What is the combination you want? What is your reason to have one set of alignments activated but another set deactivated? I can try to work this out if you give me more information.

**Comment by l0c0luke** [comment]
i guess i like the alignment of arrays and variables, but not the alignment
of chained methods. however, it does seem I can have my methods indednted
like you do and psr2 is passing. so maybe i just need to get used to it.

On Mon, Mar 9, 2015 at 2:14 PM, C Cirello <notifications@github.com> wrote:

> @l0c0luke <https://github.com/l0c0luke> makes sense - you wanted the
> alignment to be removed first place right? What is the combination you
> want? What is your reason to have one set of alignments activated but
> another set deactivated? I can try to work this out if you give me more
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/99#issuecomment-77944013>
> .
>



-- 

Luke Ollett

+1(949) 371-5292

**Comment by dericofilho** [comment]
OK! May I close this issue?

**Comment by l0c0luke** [comment]
yes

On Mon, Mar 9, 2015 at 2:17 PM, C Cirello <notifications@github.com> wrote:

> OK! May I close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dericofilho/sublime-phpfmt/issues/99#issuecomment-77944683>
> .
>



-- 

Luke Ollett

+1(949) 371-5292
